-- Generated from src/lib/supply-seed.ts. Re-run: npx tsx scripts/emit-supply-seed.ts
-- Run after 012_supply.sql. Does not truncate the live catalogue.

insert into products (id, name, name_pl, category, unit, regular_price_pln, default_unit, availability_type, is_pantry_staple)
values
('chicken-breast', 'Chicken breast', 'Chicken breast', 'Meat', 'kg', null, 'g', 'standard', false),
('chicken-thighs', 'Chicken thighs', 'Chicken thighs', 'Meat', 'kg', null, 'g', 'standard', false),
('ground-beef', 'Ground beef', 'Ground beef', 'Meat', 'kg', null, 'g', 'standard', false),
('turkey-mince', 'Turkey mince', 'Turkey mince', 'Meat', 'kg', null, 'g', 'standard', false),
('eggs', 'Eggs', 'Eggs', 'Dairy', 'szt', null, 'pc', 'standard', false),
('salmon', 'Salmon', 'Salmon', 'Fish', 'kg', null, 'g', 'standard', false),
('tuna', 'Tuna', 'Tuna', 'Fish', 'kg', null, 'g', 'standard', false),
('rice', 'Rice', 'Rice', 'Grocery', 'kg', null, 'g', 'standard', false),
('pasta', 'Pasta', 'Pasta', 'Grocery', 'kg', null, 'g', 'standard', false),
('potatoes', 'Potatoes', 'Potatoes', 'Produce', 'kg', null, 'g', 'standard', false),
('sweet-potatoes', 'Sweet potatoes', 'Sweet potatoes', 'Produce', 'kg', null, 'g', 'standard', false),
('tortilla-wraps', 'Tortilla wraps', 'Tortilla wraps', 'Grocery', 'szt', null, 'pc', 'standard', false),
('bread', 'Bread', 'Bread', 'Grocery', 'szt', null, 'pc', 'standard', false),
('couscous', 'Couscous', 'Couscous', 'Grocery', 'kg', null, 'g', 'standard', false),
('buckwheat', 'Buckwheat', 'Buckwheat', 'Grocery', 'kg', null, 'g', 'standard', false),
('oats', 'Oats', 'Oats', 'Grocery', 'kg', null, 'g', 'standard', false),
('tomatoes', 'Tomatoes', 'Tomatoes', 'Produce', 'kg', null, 'g', 'seasonal', false),
('canned-tomatoes', 'Canned tomatoes', 'Canned tomatoes', 'Grocery', 'kg', null, 'g', 'standard', false),
('onion', 'Onion', 'Onion', 'Produce', 'kg', null, 'g', 'standard', false),
('garlic', 'Garlic', 'Garlic', 'Produce', 'szt', null, 'pc', 'standard', false),
('broccoli', 'Broccoli', 'Broccoli', 'Produce', 'kg', null, 'g', 'seasonal', false),
('carrots', 'Carrots', 'Carrots', 'Produce', 'kg', null, 'g', 'standard', false),
('bell-pepper', 'Bell pepper', 'Bell pepper', 'Produce', 'kg', null, 'g', 'seasonal', false),
('spinach', 'Spinach', 'Spinach', 'Produce', 'kg', null, 'g', 'seasonal', false),
('mushrooms', 'Mushrooms', 'Mushrooms', 'Produce', 'kg', null, 'g', 'seasonal', false),
('cabbage', 'Cabbage', 'Cabbage', 'Produce', 'kg', null, 'g', 'standard', false),
('sauerkraut', 'Sauerkraut', 'Sauerkraut', 'Grocery', 'kg', null, 'g', 'standard', false),
('avocado', 'Avocado', 'Avocado', 'Produce', 'szt', null, 'pc', 'seasonal', false),
('chickpeas', 'Chickpeas', 'Chickpeas', 'Grocery', 'kg', null, 'g', 'standard', false),
('black-beans', 'Black beans', 'Black beans', 'Grocery', 'kg', null, 'g', 'standard', false),
('lentils', 'Lentils', 'Lentils', 'Grocery', 'kg', null, 'g', 'standard', false),
('greek-yogurt', 'Greek yogurt', 'Greek yogurt', 'Dairy', 'kg', null, 'g', 'standard', false),
('cottage-cheese', 'Cottage cheese', 'Cottage cheese', 'Dairy', 'kg', null, 'g', 'standard', false),
('mozzarella', 'Mozzarella', 'Mozzarella', 'Dairy', 'kg', null, 'g', 'standard', false),
('feta', 'Feta', 'Feta', 'Dairy', 'kg', null, 'g', 'standard', false),
('cheddar', 'Cheddar', 'Cheddar', 'Dairy', 'kg', null, 'g', 'standard', false),
('parmesan', 'Parmesan', 'Parmesan', 'Dairy', 'kg', null, 'g', 'standard', false),
('olive-oil', 'Olive oil', 'Olive oil', 'Pantry', 'l', null, 'ml', 'standard', true),
('soy-sauce', 'Soy sauce', 'Soy sauce', 'Pantry', 'l', null, 'ml', 'standard', true),
('honey', 'Honey', 'Honey', 'Pantry', 'kg', null, 'g', 'standard', true),
('ginger', 'Ginger', 'Ginger', 'Produce', 'kg', null, 'g', 'standard', false),
('strawberries', 'Strawberries', 'Strawberries', 'Produce', 'kg', null, 'g', 'seasonal', false)
on conflict (id) do update set
  name = excluded.name,
  name_pl = excluded.name_pl,
  category = excluded.category,
  default_unit = excluded.default_unit,
  availability_type = excluded.availability_type,
  is_pantry_staple = excluded.is_pantry_staple,
  updated_at = now();

insert into recipes (id, title, description, servings, prep_time, calories, protein_g, diet_styles, allergens, proteins, appliances, cuisines, diets)
values
('chicken-teriyaki-bowl', 'Chicken Teriyaki Rice Bowl', 'Курица, рис и брокколи в соево-медовой заправке.', 1, 25, 640, 42, array['protein-packed', 'fakeway']::text[], array['soy']::text[], array['chicken']::text[], array['stove']::text[], array['asian']::text[], array[]::text[]),
('chicken-tacos', 'Chicken Tacos with Avocado & Salsa', 'Тортильи с курицей, помидорами и авокадо.', 1, 20, 680, 40, array['fakeway', 'speedy-meals']::text[], array['gluten']::text[], array['chicken']::text[], array['stove']::text[], array['mexican']::text[], array[]::text[]),
('spaghetti-bolognese', 'Spaghetti Bolognese', 'Паста с говяжьим фаршем и томатами.', 1, 35, 720, 34, array['home-style', 'family-favs']::text[], array['gluten']::text[], array['beef']::text[], array['stove']::text[], array['italian']::text[], array[]::text[]),
('butter-chicken', 'Butter Chicken with Rice', 'Куриные бёдра в йогуртово-томатном соусе с рисом.', 1, 40, 700, 38, array['home-style', 'protein-packed']::text[], array['lactose']::text[], array['chicken']::text[], array['stove']::text[], array['indian']::text[], array[]::text[]),
('mediterranean-chicken-bowl', 'Mediterranean Chicken Bowl', 'Курица, кускус, нут, помидоры и фета.', 1, 25, 610, 44, array['healthy-comfort']::text[], array['lactose']::text[], array['chicken']::text[], array['stove']::text[], array['mediterranean']::text[], array[]::text[]),
('polish-chicken-soup', 'Polish Chicken Soup', 'Бульон с курицей, картофелем, морковью и капустой.', 1, 45, 420, 30, array['home-style', 'family-favs']::text[], array[]::text[], array['chicken']::text[], array['stove']::text[], array['polish']::text[], array[]::text[])
on conflict (id) do update set
  title = excluded.title,
  description = excluded.description,
  servings = excluded.servings,
  prep_time = excluded.prep_time,
  calories = excluded.calories,
  protein_g = excluded.protein_g,
  diet_styles = excluded.diet_styles,
  allergens = excluded.allergens,
  proteins = excluded.proteins,
  appliances = excluded.appliances,
  cuisines = excluded.cuisines,
  diets = excluded.diets,
  updated_at = now();

insert into recipe_ingredients (recipe_id, product_id, qty_per_person, quantity, unit, is_pantry_ingredient)
values
('chicken-teriyaki-bowl', 'chicken-breast', 0.3, 300, 'g', false),
('chicken-teriyaki-bowl', 'rice', 0.15, 150, 'g', false),
('chicken-teriyaki-bowl', 'broccoli', 0.2, 200, 'g', false),
('chicken-teriyaki-bowl', 'soy-sauce', 0.03, 30, 'ml', true),
('chicken-teriyaki-bowl', 'honey', 0.015, 15, 'g', true),
('chicken-teriyaki-bowl', 'garlic', 2, 2, 'pc', false),
('chicken-teriyaki-bowl', 'ginger', 0.01, 10, 'g', false),
('chicken-tacos', 'chicken-breast', 0.3, 300, 'g', false),
('chicken-tacos', 'tortilla-wraps', 4, 4, 'pc', false),
('chicken-tacos', 'tomatoes', 0.15, 150, 'g', false),
('chicken-tacos', 'avocado', 1, 1, 'pc', false),
('chicken-tacos', 'onion', 0.04, 40, 'g', false),
('spaghetti-bolognese', 'ground-beef', 0.18, 180, 'g', false),
('spaghetti-bolognese', 'pasta', 0.15, 150, 'g', false),
('spaghetti-bolognese', 'canned-tomatoes', 0.2, 200, 'g', false),
('spaghetti-bolognese', 'onion', 0.05, 50, 'g', false),
('spaghetti-bolognese', 'garlic', 1, 1, 'pc', false),
('spaghetti-bolognese', 'olive-oil', 0.01, 10, 'ml', true),
('butter-chicken', 'chicken-thighs', 0.25, 250, 'g', false),
('butter-chicken', 'rice', 0.15, 150, 'g', false),
('butter-chicken', 'greek-yogurt', 0.08, 80, 'g', false),
('butter-chicken', 'canned-tomatoes', 0.12, 120, 'g', false),
('butter-chicken', 'onion', 0.04, 40, 'g', false),
('butter-chicken', 'garlic', 2, 2, 'pc', false),
('mediterranean-chicken-bowl', 'chicken-breast', 0.22, 220, 'g', false),
('mediterranean-chicken-bowl', 'couscous', 0.08, 80, 'g', false),
('mediterranean-chicken-bowl', 'chickpeas', 0.1, 100, 'g', false),
('mediterranean-chicken-bowl', 'tomatoes', 0.08, 80, 'g', false),
('mediterranean-chicken-bowl', 'feta', 0.04, 40, 'g', false),
('mediterranean-chicken-bowl', 'olive-oil', 0.01, 10, 'ml', true),
('polish-chicken-soup', 'chicken-thighs', 0.2, 200, 'g', false),
('polish-chicken-soup', 'carrots', 0.08, 80, 'g', false),
('polish-chicken-soup', 'potatoes', 0.15, 150, 'g', false),
('polish-chicken-soup', 'onion', 0.04, 40, 'g', false),
('polish-chicken-soup', 'garlic', 1, 1, 'pc', false),
('polish-chicken-soup', 'cabbage', 0.06, 60, 'g', false)
on conflict (recipe_id, product_id) do update set
  qty_per_person = excluded.qty_per_person,
  quantity = excluded.quantity,
  unit = excluded.unit,
  is_pantry_ingredient = excluded.is_pantry_ingredient;

insert into store_products (id, product_id, store_id, name, package_quantity, package_unit, sale_mode)
values
('biedronka-chicken-breast-500', 'chicken-breast', 'biedronka', 'Chicken breast', 500, 'g', 'package'),
('biedronka-chicken-breast-1000', 'chicken-breast', 'biedronka', 'Chicken breast', 1000, 'g', 'package'),
('biedronka-chicken-thighs-500', 'chicken-thighs', 'biedronka', 'Chicken thighs', 500, 'g', 'package'),
('biedronka-ground-beef-500', 'ground-beef', 'biedronka', 'Ground beef', 500, 'g', 'package'),
('biedronka-turkey-mince-500', 'turkey-mince', 'biedronka', 'Turkey mince', 500, 'g', 'package'),
('biedronka-eggs-10', 'eggs', 'biedronka', 'Eggs', 10, 'pc', 'package'),
('biedronka-salmon-300', 'salmon', 'biedronka', 'Salmon', 300, 'g', 'package'),
('biedronka-tuna-120', 'tuna', 'biedronka', 'Tuna', 120, 'g', 'package'),
('biedronka-rice-500', 'rice', 'biedronka', 'Rice', 500, 'g', 'package'),
('biedronka-rice-1000', 'rice', 'biedronka', 'Rice', 1000, 'g', 'package'),
('biedronka-rice-2000', 'rice', 'biedronka', 'Rice', 2000, 'g', 'package'),
('biedronka-pasta-500', 'pasta', 'biedronka', 'Pasta', 500, 'g', 'package'),
('biedronka-potatoes-1000', 'potatoes', 'biedronka', 'Potatoes', 1000, 'g', 'weight'),
('biedronka-sweet-potatoes-1000', 'sweet-potatoes', 'biedronka', 'Sweet potatoes', 1000, 'g', 'weight'),
('biedronka-tortilla-6', 'tortilla-wraps', 'biedronka', 'Tortilla wraps', 6, 'pc', 'package'),
('biedronka-bread-1', 'bread', 'biedronka', 'Bread', 1, 'pc', 'package'),
('biedronka-couscous-500', 'couscous', 'biedronka', 'Couscous', 500, 'g', 'package'),
('biedronka-buckwheat-1000', 'buckwheat', 'biedronka', 'Buckwheat', 1000, 'g', 'package'),
('biedronka-oats-500', 'oats', 'biedronka', 'Oats', 500, 'g', 'package'),
('biedronka-tomatoes-1000', 'tomatoes', 'biedronka', 'Tomatoes', 1000, 'g', 'weight'),
('biedronka-canned-tomatoes-400', 'canned-tomatoes', 'biedronka', 'Canned tomatoes', 400, 'g', 'package'),
('biedronka-onion-1000', 'onion', 'biedronka', 'Onion', 1000, 'g', 'weight'),
('biedronka-garlic-1', 'garlic', 'biedronka', 'Garlic', 1, 'pc', 'package'),
('biedronka-broccoli-500', 'broccoli', 'biedronka', 'Broccoli', 500, 'g', 'package'),
('biedronka-carrots-1000', 'carrots', 'biedronka', 'Carrots', 1000, 'g', 'weight'),
('biedronka-bell-pepper-200', 'bell-pepper', 'biedronka', 'Bell pepper', 200, 'g', 'package'),
('biedronka-spinach-100', 'spinach', 'biedronka', 'Spinach', 100, 'g', 'package'),
('biedronka-mushrooms-400', 'mushrooms', 'biedronka', 'Mushrooms', 400, 'g', 'package'),
('biedronka-cabbage-1000', 'cabbage', 'biedronka', 'Cabbage', 1000, 'g', 'weight'),
('biedronka-sauerkraut-500', 'sauerkraut', 'biedronka', 'Sauerkraut', 500, 'g', 'package'),
('biedronka-avocado-1', 'avocado', 'biedronka', 'Avocado', 1, 'pc', 'package'),
('biedronka-chickpeas-400', 'chickpeas', 'biedronka', 'Chickpeas', 400, 'g', 'package'),
('biedronka-black-beans-400', 'black-beans', 'biedronka', 'Black beans', 400, 'g', 'package'),
('biedronka-lentils-500', 'lentils', 'biedronka', 'Lentils', 500, 'g', 'package'),
('biedronka-greek-yogurt-400', 'greek-yogurt', 'biedronka', 'Greek yogurt', 400, 'g', 'package'),
('biedronka-cottage-cheese-200', 'cottage-cheese', 'biedronka', 'Cottage cheese', 200, 'g', 'package'),
('biedronka-mozzarella-125', 'mozzarella', 'biedronka', 'Mozzarella', 125, 'g', 'package'),
('biedronka-feta-200', 'feta', 'biedronka', 'Feta', 200, 'g', 'package'),
('biedronka-cheddar-200', 'cheddar', 'biedronka', 'Cheddar', 200, 'g', 'package'),
('biedronka-parmesan-100', 'parmesan', 'biedronka', 'Parmesan', 100, 'g', 'package'),
('biedronka-olive-oil-500', 'olive-oil', 'biedronka', 'Olive oil', 500, 'ml', 'package'),
('biedronka-soy-sauce-150', 'soy-sauce', 'biedronka', 'Soy sauce', 150, 'ml', 'package'),
('biedronka-honey-250', 'honey', 'biedronka', 'Honey', 250, 'g', 'package'),
('biedronka-ginger-100', 'ginger', 'biedronka', 'Ginger', 100, 'g', 'package'),
('biedronka-strawberries-500', 'strawberries', 'biedronka', 'Strawberries', 500, 'g', 'package')
on conflict (id) do update set
  product_id = excluded.product_id,
  store_id = excluded.store_id,
  name = excluded.name,
  package_quantity = excluded.package_quantity,
  package_unit = excluded.package_unit,
  sale_mode = excluded.sale_mode,
  updated_at = now();

insert into prices (id, store_product_id, price, valid_from, valid_to)
values
('biedronka-chicken-breast-500-2026-10-01', 'biedronka-chicken-breast-500', 12.99, '2026-10-01', null),
('biedronka-chicken-breast-1000-2026-10-01', 'biedronka-chicken-breast-1000', 22.99, '2026-10-01', null),
('biedronka-chicken-thighs-500-2026-10-01', 'biedronka-chicken-thighs-500', 11.49, '2026-10-01', null),
('biedronka-ground-beef-500-2026-10-01', 'biedronka-ground-beef-500', 16.99, '2026-10-01', null),
('biedronka-turkey-mince-500-2026-10-01', 'biedronka-turkey-mince-500', 14.99, '2026-10-01', null),
('biedronka-eggs-10-2026-10-01', 'biedronka-eggs-10', 12.49, '2026-10-01', null),
('biedronka-salmon-300-2026-10-01', 'biedronka-salmon-300', 24.99, '2026-10-01', null),
('biedronka-tuna-120-2026-10-01', 'biedronka-tuna-120', 5.49, '2026-10-01', null),
('biedronka-rice-500-2026-10-01', 'biedronka-rice-500', 4.99, '2026-10-01', null),
('biedronka-rice-1000-2026-10-01', 'biedronka-rice-1000', 7.99, '2026-10-01', null),
('biedronka-rice-2000-2026-10-01', 'biedronka-rice-2000', 13.99, '2026-10-01', null),
('biedronka-pasta-500-2026-10-01', 'biedronka-pasta-500', 3.79, '2026-10-01', null),
('biedronka-potatoes-1000-2026-10-01', 'biedronka-potatoes-1000', 2.99, '2026-10-01', null),
('biedronka-sweet-potatoes-1000-2026-10-01', 'biedronka-sweet-potatoes-1000', 5.99, '2026-10-01', null),
('biedronka-tortilla-6-2026-10-01', 'biedronka-tortilla-6', 5.49, '2026-10-01', null),
('biedronka-bread-1-2026-10-01', 'biedronka-bread-1', 4.29, '2026-10-01', null),
('biedronka-couscous-500-2026-10-01', 'biedronka-couscous-500', 4.49, '2026-10-01', null),
('biedronka-buckwheat-1000-2026-10-01', 'biedronka-buckwheat-1000', 6.99, '2026-10-01', null),
('biedronka-oats-500-2026-10-01', 'biedronka-oats-500', 3.49, '2026-10-01', null),
('biedronka-tomatoes-1000-2026-10-01', 'biedronka-tomatoes-1000', 9.99, '2026-10-01', null),
('biedronka-canned-tomatoes-400-2026-10-01', 'biedronka-canned-tomatoes-400', 3.29, '2026-10-01', null),
('biedronka-onion-1000-2026-10-01', 'biedronka-onion-1000', 2.99, '2026-10-01', null),
('biedronka-garlic-1-2026-10-01', 'biedronka-garlic-1', 1.79, '2026-10-01', null),
('biedronka-broccoli-500-2026-10-01', 'biedronka-broccoli-500', 5.49, '2026-10-01', null),
('biedronka-carrots-1000-2026-10-01', 'biedronka-carrots-1000', 2.99, '2026-10-01', null),
('biedronka-bell-pepper-200-2026-10-01', 'biedronka-bell-pepper-200', 3.49, '2026-10-01', null),
('biedronka-spinach-100-2026-10-01', 'biedronka-spinach-100', 5.49, '2026-10-01', null),
('biedronka-mushrooms-400-2026-10-01', 'biedronka-mushrooms-400', 6.99, '2026-10-01', null),
('biedronka-cabbage-1000-2026-10-01', 'biedronka-cabbage-1000', 3.49, '2026-10-01', null),
('biedronka-sauerkraut-500-2026-10-01', 'biedronka-sauerkraut-500', 4.29, '2026-10-01', null),
('biedronka-avocado-1-2026-10-01', 'biedronka-avocado-1', 5.99, '2026-10-01', null),
('biedronka-chickpeas-400-2026-10-01', 'biedronka-chickpeas-400', 2.99, '2026-10-01', null),
('biedronka-black-beans-400-2026-10-01', 'biedronka-black-beans-400', 3.49, '2026-10-01', null),
('biedronka-lentils-500-2026-10-01', 'biedronka-lentils-500', 4.99, '2026-10-01', null),
('biedronka-greek-yogurt-400-2026-10-01', 'biedronka-greek-yogurt-400', 4.99, '2026-10-01', null),
('biedronka-cottage-cheese-200-2026-10-01', 'biedronka-cottage-cheese-200', 3.99, '2026-10-01', null),
('biedronka-mozzarella-125-2026-10-01', 'biedronka-mozzarella-125', 4.49, '2026-10-01', null),
('biedronka-feta-200-2026-10-01', 'biedronka-feta-200', 6.99, '2026-10-01', null),
('biedronka-cheddar-200-2026-10-01', 'biedronka-cheddar-200', 7.49, '2026-10-01', null),
('biedronka-parmesan-100-2026-10-01', 'biedronka-parmesan-100', 8.99, '2026-10-01', null),
('biedronka-olive-oil-500-2026-10-01', 'biedronka-olive-oil-500', 18.99, '2026-10-01', null),
('biedronka-soy-sauce-150-2026-10-01', 'biedronka-soy-sauce-150', 6.49, '2026-10-01', null),
('biedronka-honey-250-2026-10-01', 'biedronka-honey-250', 9.99, '2026-10-01', null),
('biedronka-ginger-100-2026-10-01', 'biedronka-ginger-100', 3.99, '2026-10-01', null),
('biedronka-strawberries-500-2026-10-01', 'biedronka-strawberries-500', 12.99, '2026-10-01', null)
on conflict (id) do update set
  price = excluded.price,
  valid_from = excluded.valid_from,
  valid_to = excluded.valid_to;

insert into store_promotions (id, store_product_id, regular_price, promotion_price, valid_from, valid_to)
values
('promo-strawberries-2026-10', 'biedronka-strawberries-500', 12.99, 7.99, '2026-10-01', '2026-10-07')
on conflict (id) do update set
  regular_price = excluded.regular_price,
  promotion_price = excluded.promotion_price,
  valid_from = excluded.valid_from,
  valid_to = excluded.valid_to;
