-- Generated from src/lib/catalog.ts. Re-run: npx tsx scripts/emit-seed.ts
begin;

truncate table
  recipe_ingredients,
  meal_plan_items,
  promotions,
  meal_plans,
  recipes,
  products
restart identity cascade;

insert into products (id, name_pl, category, unit, regular_price_pln) values
('pomidory', 'Pomidory', 'Овощи', 'kg', 8.99),
('ogorki', 'Ogórki', 'Овощи', 'kg', 6.49),
('cebula', 'Cebula', 'Овощи', 'kg', 3.49),
('marchew', 'Marchew', 'Овощи', 'kg', 3.29),
('ziemniaki', 'Ziemniaki', 'Овощи', 'kg', 2.99),
('papryka', 'Papryka czerwona', 'Овощи', 'kg', 12.99),
('salata', 'Sałata masłowa', 'Овощи', 'szt', 4.49),
('cukinia', 'Cukinia', 'Овощи', 'kg', 6.99),
('brokuly', 'Brokuły', 'Овощи', 'szt', 5.99),
('szpinak', 'Szpinak baby', 'Овощи', 'szt', 4.99),
('czosnek', 'Czosnek', 'Овощи', 'szt', 1.49),
('cytryna', 'Cytryna', 'Овощи', 'szt', 1.99),
('awokado', 'Awokado', 'Овощи', 'szt', 6.99),
('kurczak', 'Filet z kurczaka', 'Мясо', 'kg', 24.99),
('mielone', 'Mięso mielone wołowe', 'Мясо', 'kg', 32.99),
('schab', 'Schab wieprzowy', 'Мясо', 'kg', 22.99),
('tofu', 'Tofu naturalne', 'Мясо', 'szt', 7.49),
('losos', 'Łosoś filet', 'Рыба', 'kg', 59.99),
('dorsz', 'Dorsz filet', 'Рыба', 'kg', 39.99),
('mleko', 'Mleko 2%', 'Молочка', 'l', 3.99),
('jogurt', 'Jogurt naturalny', 'Молочка', 'szt', 2.49),
('gouda', 'Ser gouda', 'Молочка', 'kg', 39.99),
('smietana', 'Śmietana 18%', 'Молочка', 'szt', 3.29),
('jaja', 'Jaja M 10 szt.', 'Молочка', 'opak', 12.99),
('feta', 'Ser feta', 'Молочка', 'szt', 6.99),
('maslo', 'Masło ekstra', 'Молочка', 'szt', 8.99),
('ryz', 'Ryż jaśminowy', 'Бакалея', 'kg', 6.99),
('penne', 'Makaron penne', 'Бакалея', 'szt', 4.49),
('spaghetti', 'Makaron spaghetti', 'Бакалея', 'szt', 4.29),
('kasza', 'Kasza gryczana', 'Бакалея', 'kg', 7.49),
('soczewica', 'Soczewica czerwona', 'Бакалея', 'kg', 8.99),
('ciecierzyca', 'Ciecierzyca konserwowa', 'Бакалея', 'szt', 3.49),
('pomidory-puszka', 'Pomidory krojone', 'Бакалея', 'szt', 3.99),
('passata', 'Passata pomidorowa', 'Бакалея', 'szt', 5.49),
('oliwa', 'Oliwa z oliwek', 'Бакалея', 'szt', 19.99),
('tortilla', 'Tortilla pszenna', 'Бакалея', 'opak', 6.99),
('fasola', 'Fasola czerwona', 'Бакалея', 'szt', 3.79),
('kukurydza', 'Kukurydza konserwowa', 'Бакалея', 'szt', 3.59),
('chleb', 'Chleb żytni', 'Бакалея', 'szt', 4.99),
('bulka', 'Bułka kajzerka', 'Бакалея', 'szt', 0.69);

insert into recipes (id, title, diet_styles, allergens, proteins, is_vegan) values
('chicken-rice', 'Курица с рисом и брокколи', array['sport', 'healthy']::text[], array[]::text[], array['chicken']::text[], false),
('chicken-salad', 'Салат с курицей', array['healthy', 'sport']::text[], array[]::text[], array['chicken']::text[], false),
('chicken-tortilla', 'Тортилья с курицей', array['sport', 'comfort']::text[], array['gluten']::text[], array['chicken']::text[], false),
('bolognese', 'Паста болоньезе', array['comfort']::text[], array['gluten']::text[], array['beef']::text[], false),
('pork-potato', 'Свинина с картошкой', array['comfort']::text[], array[]::text[], array['pork']::text[], false),
('salmon-buckwheat', 'Лосось с гречкой и шпинатом', array['healthy', 'sport']::text[], array['fish']::text[], array['fish']::text[], false),
('beef-bake', 'Запеканка с фаршем', array['comfort']::text[], array['lactose']::text[], array['beef']::text[], false),
('omelette', 'Омлет со шпинатом и фетой', array['sport']::text[], array['eggs', 'lactose']::text[], array['veg']::text[], false),
('lentil-soup', 'Чечевичный суп', array['healthy', 'balanced']::text[], array[]::text[], array['veg']::text[], true),
('chickpea-curry', 'Нут карри с рисом', array['healthy']::text[], array[]::text[], array['veg']::text[], true),
('buckwheat-veg', 'Гречка с цукини', array['healthy', 'comfort']::text[], array[]::text[], array['veg']::text[], true),
('avocado-salad', 'Овощной салат с авокадо', array['healthy']::text[], array[]::text[], array['veg']::text[], true),
('veg-risotto', 'Овощное ризотто', array['balanced', 'comfort']::text[], array[]::text[], array['veg']::text[], true),
('lentil-pepper', 'Чечевица с паприкой', array['healthy', 'sport']::text[], array[]::text[], array['veg']::text[], true),
('chickpea-salad', 'Салат с нутом', array['healthy', 'balanced']::text[], array[]::text[], array['veg']::text[], true),
('tofu-bowl', 'Тофу с рисом и брокколи', array['sport']::text[], array['soy']::text[], array['veg']::text[], true);

insert into recipe_ingredients (recipe_id, product_id, qty_per_person) values
('chicken-rice', 'kurczak', 0.18),
('chicken-rice', 'ryz', 0.07),
('chicken-rice', 'brokuly', 0.4),
('chicken-rice', 'cebula', 0.04),
('chicken-rice', 'czosnek', 0.15),
('chicken-salad', 'kurczak', 0.15),
('chicken-salad', 'salata', 0.5),
('chicken-salad', 'pomidory', 0.12),
('chicken-salad', 'ogorki', 0.1),
('chicken-salad', 'oliwa', 0.02),
('chicken-tortilla', 'kurczak', 0.15),
('chicken-tortilla', 'tortilla', 0.5),
('chicken-tortilla', 'papryka', 0.08),
('chicken-tortilla', 'cebula', 0.03),
('chicken-tortilla', 'jogurt', 0.15),
('bolognese', 'mielone', 0.15),
('bolognese', 'penne', 0.35),
('bolognese', 'pomidory-puszka', 0.5),
('bolognese', 'cebula', 0.05),
('bolognese', 'czosnek', 0.2),
('pork-potato', 'schab', 0.18),
('pork-potato', 'ziemniaki', 0.25),
('pork-potato', 'cebula', 0.04),
('pork-potato', 'marchew', 0.05),
('salmon-buckwheat', 'losos', 0.16),
('salmon-buckwheat', 'kasza', 0.07),
('salmon-buckwheat', 'szpinak', 0.5),
('salmon-buckwheat', 'cytryna', 0.3),
('beef-bake', 'mielone', 0.15),
('beef-bake', 'ziemniaki', 0.3),
('beef-bake', 'smietana', 0.15),
('beef-bake', 'gouda', 0.04),
('beef-bake', 'cebula', 0.04),
('omelette', 'jaja', 0.2),
('omelette', 'szpinak', 0.3),
('omelette', 'feta', 0.15),
('omelette', 'cebula', 0.02),
('lentil-soup', 'soczewica', 0.08),
('lentil-soup', 'marchew', 0.08),
('lentil-soup', 'cebula', 0.05),
('lentil-soup', 'ziemniaki', 0.12),
('lentil-soup', 'czosnek', 0.15),
('lentil-soup', 'pomidory-puszka', 0.25),
('chickpea-curry', 'ciecierzyca', 1),
('chickpea-curry', 'passata', 0.3),
('chickpea-curry', 'cebula', 0.04),
('chickpea-curry', 'ryz', 0.07),
('chickpea-curry', 'szpinak', 0.3),
('chickpea-curry', 'czosnek', 0.15),
('buckwheat-veg', 'kasza', 0.08),
('buckwheat-veg', 'cukinia', 0.15),
('buckwheat-veg', 'marchew', 0.06),
('buckwheat-veg', 'cebula', 0.04),
('buckwheat-veg', 'czosnek', 0.1),
('avocado-salad', 'awokado', 0.5),
('avocado-salad', 'pomidory', 0.15),
('avocado-salad', 'ogorki', 0.1),
('avocado-salad', 'cebula', 0.02),
('avocado-salad', 'cytryna', 0.25),
('avocado-salad', 'oliwa', 0.02),
('veg-risotto', 'ryz', 0.08),
('veg-risotto', 'cukinia', 0.12),
('veg-risotto', 'marchew', 0.05),
('veg-risotto', 'cebula', 0.04),
('veg-risotto', 'szpinak', 0.25),
('veg-risotto', 'czosnek', 0.1),
('lentil-pepper', 'soczewica', 0.09),
('lentil-pepper', 'papryka', 0.12),
('lentil-pepper', 'cebula', 0.04),
('lentil-pepper', 'pomidory-puszka', 0.4),
('lentil-pepper', 'czosnek', 0.15),
('chickpea-salad', 'ciecierzyca', 0.8),
('chickpea-salad', 'ogorki', 0.1),
('chickpea-salad', 'pomidory', 0.12),
('chickpea-salad', 'cebula', 0.03),
('chickpea-salad', 'cytryna', 0.2),
('tofu-bowl', 'tofu', 0.5),
('tofu-bowl', 'ryz', 0.07),
('tofu-bowl', 'brokuly', 0.4),
('tofu-bowl', 'papryka', 0.08),
('tofu-bowl', 'czosnek', 0.1);

insert into promotions (id, product_id, promo_price_pln, valid_from, valid_to, label)
select id, product_id, promo_price_pln, valid_from, valid_to, label
from (
  select
    date_trunc('week', current_date)::date as mon,
    (date_trunc('week', current_date)::date + 5) as mon_to,
    (date_trunc('week', current_date)::date + 3) as thu,
    (date_trunc('week', current_date)::date + 6) as thu_to
) bounds
cross join lateral (
  values
('gazetka-pon-0-kurczak', 'kurczak', 16.99, bounds.mon, bounds.mon_to, 'gazetka-pon'), ('gazetka-pon-1-kurczak', 'kurczak', 16.99, bounds.mon + 7, bounds.mon_to + 7, 'gazetka-pon'),
('gazetka-pon-0-ryz', 'ryz', 3.99, bounds.mon, bounds.mon_to, 'gazetka-pon'), ('gazetka-pon-1-ryz', 'ryz', 3.99, bounds.mon + 7, bounds.mon_to + 7, 'gazetka-pon'),
('gazetka-pon-0-pomidory', 'pomidory', 4.99, bounds.mon, bounds.mon_to, 'gazetka-pon'), ('gazetka-pon-1-pomidory', 'pomidory', 4.99, bounds.mon + 7, bounds.mon_to + 7, 'gazetka-pon'),
('gazetka-pon-0-penne', 'penne', 2.49, bounds.mon, bounds.mon_to, 'gazetka-pon'), ('gazetka-pon-1-penne', 'penne', 2.49, bounds.mon + 7, bounds.mon_to + 7, 'gazetka-pon'),
('gazetka-pon-0-jogurt', 'jogurt', 1.29, bounds.mon, bounds.mon_to, 'gazetka-pon'), ('gazetka-pon-1-jogurt', 'jogurt', 1.29, bounds.mon + 7, bounds.mon_to + 7, 'gazetka-pon'),
('gazetka-pon-0-ziemniaki', 'ziemniaki', 1.49, bounds.mon, bounds.mon_to, 'gazetka-pon'), ('gazetka-pon-1-ziemniaki', 'ziemniaki', 1.49, bounds.mon + 7, bounds.mon_to + 7, 'gazetka-pon'),
('gazetka-pon-0-cebula', 'cebula', 1.99, bounds.mon, bounds.mon_to, 'gazetka-pon'), ('gazetka-pon-1-cebula', 'cebula', 1.99, bounds.mon + 7, bounds.mon_to + 7, 'gazetka-pon'),
('gazetka-pon-0-marchew', 'marchew', 1.79, bounds.mon, bounds.mon_to, 'gazetka-pon'), ('gazetka-pon-1-marchew', 'marchew', 1.79, bounds.mon + 7, bounds.mon_to + 7, 'gazetka-pon'),
('gazetka-pon-0-jaja', 'jaja', 7.99, bounds.mon, bounds.mon_to, 'gazetka-pon'), ('gazetka-pon-1-jaja', 'jaja', 7.99, bounds.mon + 7, bounds.mon_to + 7, 'gazetka-pon'),
('gazetka-pon-0-soczewica', 'soczewica', 4.99, bounds.mon, bounds.mon_to, 'gazetka-pon'), ('gazetka-pon-1-soczewica', 'soczewica', 4.99, bounds.mon + 7, bounds.mon_to + 7, 'gazetka-pon'),
('gazetka-pon-0-pomidory-puszka', 'pomidory-puszka', 2.29, bounds.mon, bounds.mon_to, 'gazetka-pon'), ('gazetka-pon-1-pomidory-puszka', 'pomidory-puszka', 2.29, bounds.mon + 7, bounds.mon_to + 7, 'gazetka-pon'),
('gazetka-pon-0-kasza', 'kasza', 4.49, bounds.mon, bounds.mon_to, 'gazetka-pon'), ('gazetka-pon-1-kasza', 'kasza', 4.49, bounds.mon + 7, bounds.mon_to + 7, 'gazetka-pon'),
('gazetka-czw-0-losos', 'losos', 36.99, bounds.thu, bounds.thu_to, 'gazetka-czw'), ('gazetka-czw-1-losos', 'losos', 36.99, bounds.thu + 7, bounds.thu_to + 7, 'gazetka-czw'),
('gazetka-czw-0-brokuly', 'brokuly', 3.49, bounds.thu, bounds.thu_to, 'gazetka-czw'), ('gazetka-czw-1-brokuly', 'brokuly', 3.49, bounds.thu + 7, bounds.thu_to + 7, 'gazetka-czw'),
('gazetka-czw-0-feta', 'feta', 3.99, bounds.thu, bounds.thu_to, 'gazetka-czw'), ('gazetka-czw-1-feta', 'feta', 3.99, bounds.thu + 7, bounds.thu_to + 7, 'gazetka-czw'),
('gazetka-czw-0-schab', 'schab', 14.99, bounds.thu, bounds.thu_to, 'gazetka-czw'), ('gazetka-czw-1-schab', 'schab', 14.99, bounds.thu + 7, bounds.thu_to + 7, 'gazetka-czw'),
('gazetka-czw-0-gouda', 'gouda', 24.99, bounds.thu, bounds.thu_to, 'gazetka-czw'), ('gazetka-czw-1-gouda', 'gouda', 24.99, bounds.thu + 7, bounds.thu_to + 7, 'gazetka-czw'),
('gazetka-czw-0-ciecierzyca', 'ciecierzyca', 1.99, bounds.thu, bounds.thu_to, 'gazetka-czw'), ('gazetka-czw-1-ciecierzyca', 'ciecierzyca', 1.99, bounds.thu + 7, bounds.thu_to + 7, 'gazetka-czw'),
('gazetka-czw-0-szpinak', 'szpinak', 2.99, bounds.thu, bounds.thu_to, 'gazetka-czw'), ('gazetka-czw-1-szpinak', 'szpinak', 2.99, bounds.thu + 7, bounds.thu_to + 7, 'gazetka-czw'),
('gazetka-czw-0-smietana', 'smietana', 1.79, bounds.thu, bounds.thu_to, 'gazetka-czw'), ('gazetka-czw-1-smietana', 'smietana', 1.79, bounds.thu + 7, bounds.thu_to + 7, 'gazetka-czw'),
('gazetka-czw-0-awokado', 'awokado', 3.99, bounds.thu, bounds.thu_to, 'gazetka-czw'), ('gazetka-czw-1-awokado', 'awokado', 3.99, bounds.thu + 7, bounds.thu_to + 7, 'gazetka-czw'),
('gazetka-czw-0-cukinia', 'cukinia', 3.99, bounds.thu, bounds.thu_to, 'gazetka-czw'), ('gazetka-czw-1-cukinia', 'cukinia', 3.99, bounds.thu + 7, bounds.thu_to + 7, 'gazetka-czw'),
('gazetka-czw-0-tofu', 'tofu', 4.49, bounds.thu, bounds.thu_to, 'gazetka-czw'), ('gazetka-czw-1-tofu', 'tofu', 4.49, bounds.thu + 7, bounds.thu_to + 7, 'gazetka-czw'),
('gazetka-czw-0-dorsz', 'dorsz', 24.99, bounds.thu, bounds.thu_to, 'gazetka-czw'), ('gazetka-czw-1-dorsz', 'dorsz', 24.99, bounds.thu + 7, bounds.thu_to + 7, 'gazetka-czw')
) as promo(id, product_id, promo_price_pln, valid_from, valid_to, label);

commit;
