export const TITLES = [
  "Tacos z kurczakiem, awokado i salsą",
  "Miska burrito z wołowiną i fasolą",
  "Quesadilla z kurczakiem",
  "Chili z indyka i fasoli",
  "Kurczak z ryżem po meksykańsku",
  "Miska fajita z wołowiną",
  "Zapiekanka enchilada z kurczakiem",
  "Wrap z tuńczykiem i kukurydzą",
  "Tacos z batatem i czarną fasolą",
  "Miska nachos z kurczakiem",
  "Makaron z kurczakiem w kremowym sosie pomidorowym",
  "Spaghetti bolognese",
  "Makaron z kurczakiem i pesto",
  "Makaron z tuńczykiem i pomidorami",
  "Makaron z kiełbasą i pomidorami z jednej patelni",
  "Zapiekanka z makaronem, szpinakiem i ricottą",
  "Makaron z kurczakiem, czosnkiem i brokułami",
  "Gnocchi z pomidorami i mozzarellą",
  "Makaron z tuńczykiem po śródziemnomorsku",
  "Makaron z kurczakiem arrabbiata",
  "Makaron z kurczakiem i pieczarkami w śmietanie",
  "Kurczak z białą fasolą z patelni",
  "Klopsiki z indyka w sosie pomidorowym",
  "Kurczak caprese",
  "Makaron z kurczakiem, cytryną i czosnkiem",
  "Kurczak maślany z ryżem",
  "Kurczak tikka masala",
  "Curry z kurczakiem i mlekiem kokosowym",
  "Curry z ciecierzycą i szpinakiem",
  "Dal z soczewicy z ryżem",
  "Curry z kurczaka i pieczone warzywa",
  "Curry z soczewicy i pomidorów",
  "Curry z kurczakiem i ziemniakami",
  "Miska ryżu z ciecierzycą",
  "Wrap tikka z kurczakiem",
  "Dal z soczewicy i mlekiem kokosowym",
  "Curry z jajek i pomidorów",
  "Kurczak korma z ryżem",
  "Klopsiki z indyka w sosie curry",
  "Warzywne curry z ciecierzycą",
  "Miska ryżu z kurczakiem teriyaki",
  "Wołowina z brokułami",
  "Smażony ryż z kurczakiem",
  "Smażony ryż z jajkiem i warzywami",
  "Kurczak w słodkim chili z ryżem",
  "Makaron z kurczakiem i czosnkiem",
  "Makaron z wołowiną",
  "Kurczak sezamowy z ryżem",
  "Makaron z kurczakiem i masłem orzechowym",
  "Ramen z jajkiem i warzywami",
  "Miska ryżu z kurczakiem i imbirem",
  "Kurczak z miodem i czosnkiem",
  "Ostra miska ryżu z wołowiną",
  "Łosoś teriyaki z ryżem",
  "Udon z kurczakiem i warzywami",
  "Miska z kurczakiem po śródziemnomorsku",
  "Kurczak po grecku z ziemniakami",
  "Sałatka grecka z kurczakiem i fetą",
  "Sałatka z tuńczyka i białej fasoli",
  "Miska z ciecierzycą po śródziemnomorsku",
  "Łosoś z cytryną, czosnkiem i warzywami",
  "Souvlaki z kurczaka z ryżem",
  "Klopsiki z indyka z tzatziki",
  "Sałatka makaronowa po śródziemnomorsku",
  "Makaron z pieczoną fetą i pomidorami",
  "Miska z tuńczykiem i jajkiem",
  "Kuskus z pieczonymi warzywami i fetą",
  "Kuskus z kurczakiem i cytryną",
  "Faszerowana papryka po grecku",
  "Gulasz z kurczaka i ciecierzycy",
  "Kotlet z kurczaka z ziemniakami",
  "Rosół z kurczaka",
  "Zupa pomidorowa z ryżem",
  "Placki ziemniaczane",
  "Zupa z kurczakiem i pęczakiem",
  "Kurczak z kapustą z jednego garnka",
  "Klopsiki z indyka i ziemniaki z koperkiem",
  "Kurczak z kaszą gryczaną",
  "Kurczak pieczony z kiszoną kapustą",
  "Ziemniaki z jajkiem i koperkiem",
  "Leczo z kurczakiem",
  "Gulasz z indyka i kasza gryczana",
  "Miska z twarogiem i ziemniakami",
  "Kasza z pieczarkami i twarogiem",
  "Gołąbki z indykiem",
  "Pęczak z kurczakiem i pieczarkami",
  "Indyk z warzywami z patelni",
  "Pieczone ziemniaki z twarogiem",
  "Warzywny gulasz",
  "Kurczak z kiszoną kapustą",
  "Burger z kurczakiem i frytkami z piekarnika",
  "Gyros z kurczaka",
  "Wrap z chrupiącym kurczakiem",
  "Miska cheeseburger z wołowiną",
  "Wrap Caesar z kurczakiem",
  "Pizza na tortilli",
  "Miska shawarma z kurczakiem",
  "Pieczony ziemniak z kurczakiem i serem",
  "Ryż z chrupiącym kurczakiem i ostrym majonezem",
  "Domowe burrito z kurczakiem",
];

export const STEPS = [
  ["Przyprawionego kurczaka smaż na oleju 5–7 minut z każdej strony i pokrój.", "Podgrzej tortille.", "Nałóż kurczaka, awokado, pomidora i cebulę, na koniec skrop limonką."],
  ["Wołowinę zrumień z kuminem i papryką.", "W misce ułóż ciepły ryż, fasolę, kukurydzę, mięso i pomidora.", "Dodaj awokado i jogurt, skrop limonką."],
  ["Usmaż kurczaka z papryką i cebulą.", "Na tortillę połóż farsz i cheddar, przykryj drugą i opiecz z obu stron, aż ser się stopi.", "Podawaj z salsą."],
  ["Podsmaż cebulę, paprykę i czosnek. Dodaj indyka i zrumień.", "Wlej pomidory, dodaj fasolę i przyprawy. Duś 20–25 minut, aż zgęstnieje."],
  ["Zrumień kawałki kurczaka. Dodaj cebulę i paprykę, potem pomidory i przyprawy.", "Wmieszaj ugotowany ryż i kukurydzę, grzej 5–7 minut."],
  ["Wołowinę szybko obsmaż na dużym ogniu.", "Dodaj paprykę i cebulę i smaż, aż lekko się przypalą.", "Podawaj na ryżu z awokado i limonką."],
  ["Ugotowanego kurczaka, fasolę i cebulę zawiń w tortille.", "Ułóż w naczyniu, polej sosem i posyp cheddarem.", "Piecz 20 minut w 190°C, na wierzch daj jogurt."],
  ["Tuńczyka wymieszaj z jogurtem, limonką i pieprzem.", "Rozsmaruj na wrapie, dodaj kukurydzę, pomidora i sałatę.", "Zwiń ciasno i przekrój."],
  ["Batata pokrój w kostkę i piecz 25–30 minut w 200°C z kuminem.", "Podgrzej tortille i nałóż batata, fasolę, awokado, pomidora i cebulę."],
  ["Usmaż i pokrój kurczaka.", "W misce ułóż ryż, fasolę, kukurydzę i kurczaka.", "Dodaj pokruszone chipsy, ser, salsę i awokado."],
  ["Ugotuj makaron. Kurczaka zrumień z czosnkiem, dodaj passatę i śmietankę, duś 5 minut.", "Wymieszaj z makaronem i parmezanem."],
  ["Podsmaż cebulę i marchewkę, dodaj wołowinę i zrumień.", "Wlej passatę i duś 20 minut.", "Ugotuj spaghetti, wymieszaj z sosem i posyp parmezanem."],
  ["Ugotuj makaron i zostaw odrobinę wody z gotowania. Kurczaka usmaż na patelni.", "Makaron wymieszaj z pesto, pomidorami, szpinakiem i wodą z makaronu. Dodaj kurczaka i parmezan."],
  ["Ugotuj makaron. Czosnek i pomidory podsmaż, dodaj passatę i odsączonego tuńczyka.", "Duś 5 minut, wymieszaj z makaronem i pietruszką."],
  ["Kiełbasę i cebulę zrumień na dużej patelni.", "Dodaj pomidory, makaron i tyle wody, żeby makaron się ugotował.", "Gotuj do miękkości, wmieszaj szpinak i mozzarellę."],
  ["Makaron ugotuj prawie al dente. Wymieszaj z ricottą, szpinakiem, czosnkiem i passatą.", "Przełóż do naczynia, posyp mozzarellą i parmezanem. Piecz 20 minut w 190°C."],
  ["Ugotuj makaron i brokuły. Kurczaka obsmaż z czosnkiem i oliwą.", "Wymieszaj makaron i brokuły z kurczakiem, sokiem z cytryny i parmezanem."],
  ["Gnocchi podsmaż na patelni, aż się zezłocą.", "Dodaj czosnek, pomidory i passatę, duś 5–7 minut.", "Wmieszaj mozzarellę i bazylię, aż ser zmięknie."],
  ["Makaron ugotuj i lekko ostudź.", "Wymieszaj z tuńczykiem, warzywami, oliwkami i fetą.", "Skrop sokiem z cytryny i oliwą."],
  ["Ugotuj makaron. Kurczaka obsmaż z czosnkiem i chili.", "Dodaj passatę i duś 8 minut. Wymieszaj z makaronem i parmezanem."],
  ["Ugotuj makaron. Pieczarki i kurczaka podsmaż z czosnkiem.", "Dodaj śmietankę i parmezan, chwilę pogotuj. Wymieszaj z makaronem."],
  ["Kurczaka i cebulę zrumień. Dodaj pomidory, fasolę i zioła, duś 12–15 minut.", "Na końcu wmieszaj szpinak."],
  ["Indyka wymieszaj z jajkiem, bułką tartą i przyprawami, uformuj klopsiki.", "Zrumień na patelni, zalej passatą i duś pod przykryciem 15–20 minut.", "Posyp parmezanem."],
  ["Kurczaka przypraw i obsmaż. Na wierzch połóż mozzarellę i pomidory, przykryj, aż ser zmięknie.", "Podawaj z bazylią, sałatą i glazurą balsamiczną."],
  ["Ugotuj spaghetti. Kurczaka obsmaż z czosnkiem.", "Makaron wymieszaj z sokiem i skórką z cytryny, oliwą i parmezanem, dolej odrobinę wody z makaronu.", "Na wierzch połóż kurczaka i pietruszkę."],
  ["Cebulę i przyprawy podsmaż na maśle. Dodaj kurczaka i zrumień, potem passatę i duś.", "Jogurt wmieszaj już poza ogniem. Podawaj z ryżem."],
  ["Kurczaka zamarynuj 15 minut w jogurcie i przyprawach. Obsmaż do rumieńca.", "Duś z cebulą i sosem pomidorowym 15 minut. Podawaj z ryżem."],
  ["Kurczaka usmaż z cebulą i papryką.", "Dodaj curry i mleko kokosowe, duś 12–15 minut.", "Skrop limonką i podawaj z ryżem."],
  ["Cebulę i czosnek podsmaż z curry.", "Dodaj pomidory, ciecierzycę i mleko kokosowe, duś 15 minut.", "Wmieszaj szpinak, aż zwiędnie."],
  ["Soczewicę opłucz. Cebulę i przyprawy podsmaż, dodaj soczewicę, pomidory i wodę.", "Duś 18–20 minut, aż będzie kremowa. Podawaj z ryżem."],
  ["Ziemniaki i warzywa pokrój i piecz 25–30 minut w 200°C.", "Kurczaka usmaż z przyprawami na patelni. Podawaj razem z jogurtem."],
  ["Cebulę, czosnek i przyprawy podsmaż.", "Dodaj soczewicę, passatę i wodę, duś 18–20 minut.", "Na końcu wmieszaj szpinak."],
  ["Kurczaka i cebulę zrumień.", "Dodaj ziemniaki, pomidory, groszek, curry i tyle wody, żeby prawie przykryła.", "Duś 25 minut, aż ziemniaki zmiękną."],
  ["Ciecierzycę podgrzej na patelni z curry.", "Podawaj na ryżu z ogórkiem, pomidorem i szpinakiem.", "Na wierzch daj jogurt."],
  ["Kurczaka obtocz w jogurcie i przyprawach, usmaż do gotowości.", "Pokrój i włóż do wrapa z ogórkiem, pomidorem i sałatą. Zwiń ciasno."],
  ["Cebulę, czosnek i przyprawy podsmaż.", "Dodaj soczewicę, mleko kokosowe i wodę, duś 20 minut, aż zgęstnieje.", "Przed podaniem wmieszaj szpinak."],
  ["Cebulę i przyprawy podsmaż, dodaj pomidory i ciecierzycę, duś 8 minut.", "Zrób wgłębienia, wbij jajka, przykryj i gotuj, aż białko się zetnie.", "Dodaj szpinak."],
  ["Kurczaka usmaż z cebulą i przyprawami. Dodaj passatę i duś 10 minut.", "Zmniejsz ogień i wmieszaj jogurt.", "Podawaj z ryżem i posiekanymi nerkowcami."],
  ["Indyka wymieszaj z jajkiem i bułką tartą, uformuj klopsiki i zrumień.", "Dodaj cebulę, curry, passatę i mleko kokosowe. Duś 15 minut."],
  ["Warzywa podsmaż z curry.", "Dodaj pomidory, ciecierzycę i mleko kokosowe.", "Duś 20 minut, aż warzywa zmiękną."],
  ["Paski kurczaka obsmaż. Dodaj brokuły i marchewkę, smaż 4–5 minut.", "Wlej sos teriyaki i wymieszaj.", "Podawaj na ryżu z sezamem."],
  ["Wołowinę lekko obtocz w skrobi i obsmaż na dużym ogniu.", "Dodaj brokuły, czosnek i imbir.", "Wlej sos sojowy i odrobinę wody, smaż aż sos się zeszkli. Podawaj z ryżem."],
  ["Kurczaka usmaż na mocno rozgrzanej patelni. Dodaj marchewkę i groszek, odsuń i usmaż jajecznicę.", "Dodaj ryż i sos sojowy, smaż aż będzie gorący i lekko chrupiący."],
  ["Jajka usmaż na rozgrzanej patelni i odłóż.", "Podsmaż warzywa, dodaj ryż i sos sojowy, wmieszaj jajka i podgrzej."],
  ["Kurczaka obsmaż, dodaj paprykę i brokuły.", "Wlej słodkie chili i smaż 2–3 minuty, aż sos się sklei.", "Podawaj na ryżu z limonką."],
  ["Ugotuj makaron. Kurczaka, czosnek i warzywa smaż na dużym ogniu.", "Dodaj makaron i sos sojowy, wymieszaj 2–3 minuty."],
  ["Ugotuj makaron. Wołowinę obsmaż na dużym ogniu, dodaj warzywa.", "Wlej sosy i makaron, wymieszaj aż wszystko pokryje sos."],
  ["Wymieszaj sos sojowy, miód, czosnek i imbir.", "Kurczaka usmaż do rumieńca, dodaj sos i brokuły, redukuj aż się zeszkli.", "Podawaj z ryżem i sezamem."],
  ["Ugotuj makaron i kurczaka.", "Masło orzechowe wymieszaj z sosem sojowym, limonką, czosnkiem i odrobiną gorącej wody.", "Makaron i kurczaka wymieszaj z sosem i warzywami."],
  ["Bulion z sosem sojowym zagotuj.", "Dodaj makaron i pieczarki, potem kukurydzę i szpinak.", "Wbij jajka albo włóż ugotowane. Gotuj, aż makaron zmięknie."],
  ["Kurczaka obsmaż z imbirem.", "Dodaj warzywa i smaż, aż będą chrupiąco-miękkie.", "Wlej sos sojowy i podawaj na ryżu ze szczypiorkiem."],
  ["Kurczaka usmaż do rumieńca.", "Dodaj warzywa, potem miód, sos sojowy i czosnek.", "Smaż, aż sos pokryje wszystko. Podawaj z ryżem."],
  ["Wołowinę obsmaż z gochujang i sosem sojowym.", "Podawaj na ryżu z ogórkiem, marchewką i szczypiorkiem.", "Posyp sezamem."],
  ["Łososia upiecz albo obsmaż, żeby został lekko różowy w środku.", "Brokuły ugotuj na parze albo na patelni.", "Posmaruj łososia teriyaki i podawaj z ryżem i sezamem."],
  ["Kurczaka podsmaż z czosnkiem i imbirem.", "Dodaj warzywa i smaż, aż będą chrupiąco-miękkie.", "Dodaj udon i sos sojowy, wymieszaj aż będzie gorące."],
  ["Kurczaka usmaż i pokrój.", "W misce ułóż komosę, ciecierzycę, ogórka, pomidora i fetę.", "Skrop cytryną i oliwą."],
  ["Kurczaka i ziemniaczane ćwiartki wymieszaj z cytryną, czosnkiem, oregano i oliwą.", "Piecz 30–35 minut w 200°C, aż się zrumienią i kurczak będzie gotowy.", "Podawaj z ogórkiem."],
  ["Kurczaka usmaż na patelni albo grillu i pokrój.", "Warzywa wymieszaj z fetą i oliwkami.", "Dodaj kurczaka, skrop cytryną i oliwą."],
  ["Tuńczyka i fasolę odsącz.", "Wymieszaj z pomidorem, cebulą i pietruszką.", "Skrop cytryną i oliwą, podawaj schłodzone."],
  ["Komosę, ciecierzycę i warzywa wymieszaj.", "Dodaj fetę, skrop cytryną i oliwą.", "Podawaj w temperaturze pokojowej."],
  ["Łososia i warzywa ułóż na blasze.", "Przypraw czosnkiem, cytryną i oliwą.", "Piecz 15–20 minut w 200°C, aż łosoś się rozdziela, a warzywa zmiękną."],
  ["Kurczaka przypraw oregano i cytryną, usmaż do rumieńca.", "Pokrój i podawaj z ryżem, pitą, ogórkiem, pomidorem i jogurtem z czosnkiem."],
  ["Indyka wymieszaj z jajkiem i bułką tartą, uformuj klopsiki.", "Piecz 18–20 minut w 200°C.", "Jogurt wymieszaj z ogórkiem, czosnkiem i koperkiem i podawaj obok."],
  ["Makaron ugotuj i lekko ostudź.", "Wymieszaj z warzywami, oliwkami i fetą.", "Skrop cytryną i oliwą."],
  ["Fetę i pomidory włóż do naczynia z czosnkiem i oliwą. Piecz 20 minut w 200°C.", "Ugotuj makaron i wymieszaj z upieczoną fetą oraz szpinakiem."],
  ["Jajka ugotuj i ostudź.", "Komosę, tuńczyka i warzywa wymieszaj.", "Na wierzch połóż jajka, oliwki i fetę, skrop oliwą."],
  ["Warzywa pokrój i piecz 20–25 minut w 200°C.", "Kuskus zalej wrzątkiem.", "Wymieszaj i posyp fetą oraz ziołami."],
  ["Kurczaka i cukinię usmaż na patelni z cytryną i ziołami.", "Kuskus zalej wrzątkiem.", "Wymieszaj kuskus z ciecierzycą i połóż na wierzchu kurczaka."],
  ["Indyka i cebulę podsmaż, wymieszaj z ryżem, pomidorem i oregano.", "Napełnij papryki, posyp fetą.", "Piecz 30–35 minut w 190°C."],
  ["Kurczaka i cebulę zrumień.", "Dodaj ziemniaki, marchewkę, ciecierzycę, pomidory i wodę.", "Duś 25–30 minut, aż warzywa zmiękną."],
  ["Kurczaka rozbij i przypraw. Obtocz w mące, jajku i bułce tartej.", "Smaż na oleju, aż będzie złoty i gotowy w środku.", "Podawaj z ugotowanymi albo upieczonymi ziemniakami."],
  ["Kurczaka, warzywa i liść laurowy włóż do bulionu.", "Gotuj 25–30 minut, aż kurczak i ziemniaki zmiękną.", "Kurczaka wyjmij, rozdrobnij i włóż z powrotem. Posyp pietruszką."],
  ["Cebulę i marchewkę podsmaż. Dodaj pomidory i bulion, gotuj 20 minut.", "Zblenduj na gładko, wmieszaj ryż.", "Podawaj z jogurtem."],
  ["Ziemniaki zetrzyj i odciśnij wodę.", "Wymieszaj z jajkiem, cebulą i mąką.", "Smaż łyżki ciasta na oleju, aż będą chrupiące z obu stron. Podawaj z jogurtem i koperkiem."],
  ["Pęczak ugotuj prawie do miękkości.", "Cebulę, marchewkę i seler podsmaż, dodaj bulion, pęczak i kurczaka.", "Gotuj 20 minut, kurczaka rozdrobnij i posyp pietruszką."],
  ["Kurczaka i cebulę zrumień w garnku.", "Dodaj kapustę, ziemniaki, marchewkę, pomidory i paprykę.", "Dolej trochę wody i duś pod przykryciem 30 minut."],
  ["Indyka wymieszaj z jajkiem i bułką tartą, uformuj klopsiki i usmaż.", "Ziemniaki ugotuj, wymieszaj z koperkiem i jogurtem.", "Podawaj razem."],
  ["Ugotuj kaszę. Cebulę i marchewkę podsmaż, dodaj kurczaka i paprykę, smaż do gotowości.", "Podawaj na kaszy ze świeżym ogórkiem."],
  ["Kiszoną kapustę, jabłko, cebulę i ziemniaki ułóż w naczyniu.", "Przypraw kminkiem, połóż kurczaka na wierzchu.", "Piecz pod przykryciem 40 minut w 190°C, na końcu na chwilę odkryj."],
  ["Ziemniaki i cebulę pokrój i smaż, aż będą złote i miękkie.", "Wlej roztrzepane jajka i smaż, aż się zetną.", "Posyp koperkiem i podawaj z ogórkiem."],
  ["Kurczaka i cebulę podsmaż.", "Dodaj cukinię i paprykę, potem pomidory i fasolę.", "Przypraw papryką w proszku i duś 15–20 minut."],
  ["Indyka zrumień z cebulą.", "Dodaj marchewkę, paprykę, pomidory i paprykę w proszku, duś 15 minut.", "Podawaj z ugotowaną kaszą."],
  ["Ziemniaki ugotuj albo upiecz.", "Twaróg wymieszaj z jogurtem, koperkiem, solą i pieprzem.", "Podawaj z ziemniakami, ogórkiem i rzodkiewką."],
  ["Pieczarki i cebulę podsmaż.", "Dodaj ugotowaną kaszę i szpinak, podgrzej.", "Na wierzch połóż twaróg i koperek."],
  ["Liście kapusty zblanszuj.", "Indyka wymieszaj z ryżem, jajkiem i cebulą, zawijaj w liście.", "Ułóż w passacie, przykryj i piecz 45 minut w 190°C."],
  ["Kurczaka, pieczarki i cebulę podsmaż.", "Dodawaj pęczak i bulion partiami, mieszaj około 30 minut, aż pęczak zmięknie.", "Na końcu wmieszaj parmezan."],
  ["Indyka zrumień z cebulą.", "Dodaj warzywa i pomidory.", "Duś pod przykryciem 15–20 minut, aż warzywa zmiękną."],
  ["Ziemniaki piecz 45–60 minut w 200°C, aż będą miękkie.", "Rozkrój i napełnij twarogiem wymieszanym z jogurtem i szczypiorkiem."],
  ["Cebulę podsmaż, dodaj pokrojone warzywa i pomidory.", "Dolej wodę i duś 25–30 minut.", "Pod koniec wmieszaj fasolę."],
  ["Kurczaka i cebulę zrumień.", "Dodaj kiszoną kapustę, ziemniaka i jabłko oraz trochę wody.", "Przykryj i duś 25 minut, przed podaniem wmieszaj musztardę."],
  ["Kurczaka obtocz w jajku i bułce tartej.", "Kurczaka i ziemniaczane ćwiartki piecz 20–25 minut w 210°C, raz obróć.", "Złóż burgera z sałatą, pomidorem i sosem jogurtowym."],
  ["Kurczaka przypraw papryką, kuminem i czosnkiem, usmaż do rumieńca.", "Pokrój i napełnij pitę warzywami oraz jogurtem z czosnkiem."],
  ["Paski kurczaka obtocz w jajku i bułce tartej, smaż albo piecz w frytkownicy, aż będą chrupiące.", "Wrap napełnij sałatą, pomidorem i sosem jogurtowym."],
  ["Wołowinę zrumień z cebulą.", "W misce ułóż ryż, sałatę, pomidora, ogórki i mięso.", "Na wierzch daj cheddar i sos burgerowy."],
  ["Panierowanego kurczaka usmaż na patelni albo w frytkownicy.", "Jogurt wymieszaj z cytryną, czosnkiem i parmezanem.", "Wrap napełnij sałatą, kurczakiem i sosem."],
  ["Tortillę posmaruj passatą.", "Nałóż ugotowanego kurczaka, paprykę i mozzarellę.", "Piecz 8–12 minut w 220°C, aż będzie chrupiąca, a ser się stopi. Posyp oregano."],
  ["Kurczaka przypraw, usmaż i pokrój.", "Do miski włóż ryż, hummus i warzywa.", "Polej tahini i posyp papryką."],
  ["Ziemniaka piecz 50–60 minut w 200°C.", "Kurczaka usmaż i pokrój.", "Ziemniaka rozkrój, rozluźnij miąższ i napełnij kurczakiem, serem, jogurtem i szczypiorkiem."],
  ["Kurczaka obtocz w jajku i panko, upiecz w frytkownicy albo w piekarniku, aż będzie chrupiący.", "Majonez wymieszaj ze srirachą.", "Podawaj kurczaka na ryżu z ogórkiem i ostrym majonezem."],
  ["Kurczaka usmaż i pokrój.", "Na tortillę nałóż ryż, fasolę, kurczaka, ser, salsę, awokado i jogurt.", "Zwiń ciasno i opiecz na patelni, szwem do dołu."],
];
