-- Polish Henzo menu. Replaces the old recipe rows. Products are upserted so ingredient foreign keys resolve.
-- Safe to run again.

alter table recipes add column if not exists prep_time integer;
alter table recipes add column if not exists calories integer;
alter table recipes add column if not exists protein_g numeric(6, 1);
alter table recipes add column if not exists fat_g numeric(6, 1);
alter table recipes add column if not exists carbs_g numeric(6, 1);
alter table recipes add column if not exists steps text[] not null default '{}';
alter table recipes add column if not exists cuisines text[] not null default '{}';
alter table recipes add column if not exists diets text[] not null default '{}';

alter table recipe_ingredients alter column qty_per_person type numeric(12, 6);
alter table recipe_ingredients alter column quantity type numeric(12, 6);

create table if not exists recipe_pantry (
  recipe_id text not null references recipes (id) on delete cascade,
  name text not null,
  grams numeric(8, 1),
  primary key (recipe_id, name)
);
alter table recipe_pantry enable row level security;
drop policy if exists recipe_pantry_read on recipe_pantry;
create policy recipe_pantry_read on recipe_pantry for select to anon, authenticated using (true);

insert into products (id, name_pl, name, category, unit, default_unit, regular_price_pln, availability_type, is_pantry_staple) values
  ('pomidory', 'Pomidory', 'Pomidory', 'vegetables', 'kg', 'kg', 9.99, 'seasonal', false),
  ('ogorki', 'Ogórki', 'Ogórki', 'vegetables', 'kg', 'kg', 6.99, 'standard', false),
  ('cebula', 'Cebula', 'Cebula', 'vegetables', 'kg', 'kg', 2.99, 'standard', false),
  ('marchew', 'Marchew', 'Marchew', 'vegetables', 'kg', 'kg', 2.99, 'standard', false),
  ('ziemniaki', 'Ziemniaki', 'Ziemniaki', 'vegetables', 'kg', 'kg', 2.99, 'standard', false),
  ('papryka', 'Papryka czerwona', 'Papryka czerwona', 'vegetables', 'kg', 'kg', 12.99, 'standard', false),
  ('salata', 'Sałata masłowa', 'Sałata masłowa', 'vegetables', 'szt', 'pc', 3.99, 'standard', false),
  ('cukinia', 'Cukinia', 'Cukinia', 'vegetables', 'kg', 'kg', 6.49, 'seasonal', false),
  ('brokuly', 'Brokuły', 'Brokuły', 'vegetables', 'szt', 'pc', 5.49, 'seasonal', false),
  ('szpinak', 'Szpinak baby', 'Szpinak baby', 'vegetables', 'szt', 'pc', 5.49, 'seasonal', false),
  ('czosnek', 'Czosnek', 'Czosnek', 'vegetables', 'szt', 'pc', 1.79, 'standard', false),
  ('cytryna', 'Cytryna', 'Cytryna', 'vegetables', 'szt', 'pc', 1.69, 'standard', false),
  ('awokado', 'Awokado', 'Awokado', 'vegetables', 'szt', 'pc', 5.99, 'seasonal', false),
  ('kurczak', 'Filet z kurczaka', 'Filet z kurczaka', 'meat', 'kg', 'kg', 25.49, 'standard', false),
  ('mielone', 'Mięso mielone wołowe', 'Mięso mielone wołowe', 'meat', 'kg', 'kg', 34.99, 'standard', false),
  ('losos', 'Łosoś filet', 'Łosoś filet', 'fish', 'kg', 'kg', 62.99, 'standard', false),
  ('jogurt', 'Jogurt naturalny', 'Jogurt naturalny', 'dairy', 'szt', 'pc', 3.49, 'standard', false),
  ('jaja', 'Jaja M 10 szt.', 'Jaja M 10 szt.', 'dairy', 'opak', 'pc', 12.49, 'standard', false),
  ('feta', 'Ser feta', 'Ser feta', 'dairy', 'szt', 'pc', 6.99, 'standard', false),
  ('maslo', 'Masło ekstra', 'Masło ekstra', 'dairy', 'szt', 'pc', 7.99, 'standard', true),
  ('ryz', 'Ryż jaśminowy', 'Ryż jaśminowy', 'grocery', 'kg', 'kg', 5.99, 'standard', false),
  ('penne', 'Makaron penne', 'Makaron penne', 'grocery', 'szt', 'pc', 3.79, 'standard', false),
  ('spaghetti', 'Makaron spaghetti', 'Makaron spaghetti', 'grocery', 'szt', 'pc', 3.49, 'standard', false),
  ('kasza', 'Kasza gryczana', 'Kasza gryczana', 'grocery', 'kg', 'kg', 6.99, 'standard', false),
  ('soczewica', 'Soczewica czerwona', 'Soczewica czerwona', 'grocery', 'kg', 'kg', 8.49, 'standard', false),
  ('ciecierzyca', 'Ciecierzyca konserwowa', 'Ciecierzyca konserwowa', 'grocery', 'szt', 'pc', 2.99, 'standard', false),
  ('pomidory-puszka', 'Pomidory krojone', 'Pomidory krojone', 'grocery', 'szt', 'pc', 3.29, 'standard', false),
  ('passata', 'Passata pomidorowa', 'Passata pomidorowa', 'grocery', 'szt', 'pc', 4.79, 'standard', false),
  ('oliwa', 'Oliwa z oliwek', 'Oliwa z oliwek', 'grocery', 'szt', 'pc', 18.99, 'standard', true),
  ('tortilla', 'Tortilla pszenna', 'Tortilla pszenna', 'grocery', 'opak', 'pc', 5.49, 'standard', false),
  ('fasola', 'Fasola czerwona', 'Fasola czerwona', 'grocery', 'szt', 'pc', 3.29, 'standard', false),
  ('kukurydza', 'Kukurydza konserwowa', 'Kukurydza konserwowa', 'grocery', 'szt', 'pc', 2.99, 'standard', false),
  ('indyk', 'Mięso mielone z indyka', 'Mięso mielone z indyka', 'meat', 'kg', 'kg', 27.99, 'standard', false),
  ('udka', 'Udka z kurczaka', 'Udka z kurczaka', 'meat', 'kg', 'kg', 14.99, 'standard', false),
  ('wolowina', 'Wołowina na patelnię', 'Wołowina na patelnię', 'meat', 'kg', 'kg', 42.99, 'standard', false),
  ('kielbasa', 'Kiełbasa z kurczaka', 'Kiełbasa z kurczaka', 'meat', 'kg', 'kg', 19.99, 'standard', false),
  ('batat', 'Batat', 'Batat', 'vegetables', 'kg', 'kg', 6.99, 'standard', false),
  ('pieczarki', 'Pieczarki', 'Pieczarki', 'vegetables', 'kg', 'kg', 11.99, 'standard', false),
  ('kapusta', 'Kapusta biała', 'Kapusta biała', 'vegetables', 'kg', 'kg', 3.49, 'standard', false),
  ('seler', 'Seler naciowy', 'Seler naciowy', 'vegetables', 'kg', 'kg', 7.99, 'standard', false),
  ('jablko', 'Jabłka', 'Jabłka', 'vegetables', 'kg', 'kg', 4.49, 'standard', false),
  ('baklazan', 'Bakłażan', 'Bakłażan', 'vegetables', 'kg', 'kg', 8.99, 'standard', false),
  ('kalafior', 'Kalafior', 'Kalafior', 'vegetables', 'szt', 'pc', 6.99, 'standard', false),
  ('rzodkiewka', 'Rzodkiewka', 'Rzodkiewka', 'vegetables', 'szt', 'pc', 2.99, 'standard', false),
  ('limonka', 'Limonka', 'Limonka', 'vegetables', 'szt', 'pc', 1.99, 'standard', false),
  ('tunczyk', 'Tuńczyk w wodzie', 'Tuńczyk w wodzie', 'fish', 'szt', 'pc', 5.99, 'standard', false),
  ('jogurt-grecki', 'Jogurt grecki', 'Jogurt grecki', 'dairy', 'szt', 'pc', 3.99, 'standard', false),
  ('cheddar', 'Ser cheddar', 'Ser cheddar', 'dairy', 'kg', 'kg', 36.99, 'standard', false),
  ('parmezan', 'Parmezan', 'Parmezan', 'dairy', 'kg', 'kg', 69.99, 'standard', false),
  ('mozzarella', 'Mozzarella', 'Mozzarella', 'dairy', 'kg', 'kg', 32.99, 'standard', false),
  ('ricotta', 'Ricotta', 'Ricotta', 'dairy', 'kg', 'kg', 24.99, 'standard', false),
  ('twarog', 'Twaróg półtłusty', 'Twaróg półtłusty', 'dairy', 'kg', 'kg', 16.99, 'standard', false),
  ('smietanka', 'Śmietanka 30%', 'Śmietanka 30%', 'dairy', 'szt', 'pc', 3.79, 'standard', false),
  ('gnocchi', 'Gnocchi', 'Gnocchi', 'grocery', 'kg', 'kg', 11.99, 'standard', false),
  ('kuskus', 'Kuskus', 'Kuskus', 'grocery', 'kg', 'kg', 7.99, 'standard', false),
  ('peczak', 'Pęczak', 'Pęczak', 'grocery', 'kg', 'kg', 4.99, 'standard', false),
  ('quinoa', 'Komosa ryżowa', 'Komosa ryżowa', 'grocery', 'kg', 'kg', 14.99, 'standard', false),
  ('makaron', 'Makaron jajeczny', 'Makaron jajeczny', 'grocery', 'kg', 'kg', 9.99, 'standard', false),
  ('udon', 'Makaron udon', 'Makaron udon', 'grocery', 'kg', 'kg', 12.99, 'standard', false),
  ('ramen', 'Makaron ramen', 'Makaron ramen', 'grocery', 'kg', 'kg', 11.99, 'standard', false),
  ('fasola-czarna', 'Fasola czarna', 'Fasola czarna', 'grocery', 'szt', 'pc', 3.49, 'standard', false),
  ('fasola-biala', 'Fasola biała', 'Fasola biała', 'grocery', 'szt', 'pc', 3.49, 'standard', false),
  ('kiszona', 'Kapusta kiszona', 'Kapusta kiszona', 'grocery', 'kg', 'kg', 6.49, 'standard', false),
  ('mleczko', 'Mleko kokosowe', 'Mleko kokosowe', 'grocery', 'szt', 'pc', 4.99, 'standard', false),
  ('salsa', 'Salsa pomidorowa', 'Salsa pomidorowa', 'grocery', 'szt', 'pc', 5.49, 'standard', false),
  ('pesto', 'Pesto bazyliowe', 'Pesto bazyliowe', 'grocery', 'szt', 'pc', 8.99, 'standard', false),
  ('oliwki', 'Oliwki', 'Oliwki', 'grocery', 'szt', 'pc', 6.49, 'standard', false),
  ('groch', 'Groszek', 'Groszek', 'grocery', 'kg', 'kg', 7.99, 'standard', false),
  ('bulka-tarta', 'Bułka tarta', 'Bułka tarta', 'grocery', 'kg', 'kg', 5.99, 'standard', false),
  ('panko', 'Panko', 'Panko', 'grocery', 'kg', 'kg', 12.99, 'standard', false),
  ('pita', 'Pita', 'Pita', 'grocery', 'szt', 'pc', 1.49, 'standard', false),
  ('bulka-burger', 'Bułka burgerowa', 'Bułka burgerowa', 'grocery', 'szt', 'pc', 2.29, 'standard', false),
  ('tortilla-kukurydza', 'Tortilla kukurydziana', 'Tortilla kukurydziana', 'grocery', 'opak', 'pc', 6.49, 'standard', false),
  ('chipsy', 'Chipsy tortilla', 'Chipsy tortilla', 'grocery', 'szt', 'pc', 5.49, 'standard', false),
  ('bulion', 'Bulion warzywny', 'Bulion warzywny', 'grocery', 'l', 'l', 3.99, 'standard', false),
  ('teriyaki', 'Sos teriyaki', 'Sos teriyaki', 'grocery', 'szt', 'pc', 7.49, 'standard', false),
  ('chili-sos', 'Sos słodkie chili', 'Sos słodkie chili', 'grocery', 'szt', 'pc', 6.99, 'standard', false),
  ('ostryga', 'Sos ostrygowy', 'Sos ostrygowy', 'grocery', 'szt', 'pc', 8.49, 'standard', false),
  ('gochujang', 'Gochujang', 'Gochujang', 'grocery', 'szt', 'pc', 9.99, 'standard', false),
  ('maslo-orzechowe', 'Masło orzechowe', 'Masło orzechowe', 'grocery', 'szt', 'pc', 8.99, 'standard', false),
  ('orzechy', 'Orzechy nerkowca', 'Orzechy nerkowca', 'grocery', 'kg', 'kg', 46.99, 'standard', false),
  ('miod', 'Miód', 'Miód', 'grocery', 'szt', 'pc', 12.99, 'standard', false),
  ('hummus', 'Hummus', 'Hummus', 'grocery', 'szt', 'pc', 5.49, 'standard', false),
  ('tahini', 'Tahini', 'Tahini', 'grocery', 'szt', 'pc', 9.99, 'standard', false),
  ('majonez', 'Majonez lekki', 'Majonez lekki', 'grocery', 'szt', 'pc', 5.99, 'standard', false),
  ('sriracha', 'Sriracha', 'Sriracha', 'grocery', 'szt', 'pc', 8.49, 'standard', false),
  ('ogorki-kiszone', 'Ogórki kiszone', 'Ogórki kiszone', 'grocery', 'kg', 'kg', 7.99, 'standard', false),
  ('sos-burger', 'Sos burgerowy', 'Sos burgerowy', 'grocery', 'szt', 'pc', 4.99, 'standard', false),
  ('musztarda', 'Musztarda', 'Musztarda', 'grocery', 'szt', 'pc', 3.49, 'standard', false)
on conflict (id) do update set
  name_pl = excluded.name_pl,
  name = excluded.name,
  category = excluded.category,
  unit = excluded.unit,
  default_unit = excluded.default_unit,
  regular_price_pln = excluded.regular_price_pln,
  availability_type = excluded.availability_type,
  is_pantry_staple = excluded.is_pantry_staple;

alter table meal_plan_items drop constraint if exists meal_plan_items_recipe_id_fkey;

delete from recipes;

insert into recipes (id, title, diet_styles, allergens, proteins, appliances, cuisines, diets, description, servings, prep_time, calories, protein_g, fat_g, carbs_g, steps) values
  ('h01', 'Tacos z kurczakiem, awokado i salsą', array['protein-packed', 'speedy-meals', 'low-calories']::text[], array['gluten']::text[], array['chicken']::text[], array['stove']::text[], array['mexican']::text[], '{}'::text[], '', 1, 7, 520, 46, 20, 38, array['Przyprawionego kurczaka smaż na oleju 5–7 minut z każdej strony i pokrój.', 'Podgrzej tortille.', 'Nałóż kurczaka, awokado, pomidora i cebulę, na koniec skrop limonką.']::text[]),
  ('h02', 'Miska burrito z wołowiną i fasolą', array['protein-packed', 'healthy-comfort', 'gut-friendly']::text[], array['lactose']::text[], array['beef']::text[], array['stove']::text[], array['mexican']::text[], '{}'::text[], '', 1, 30, 680, 48, 24, 65, array['Wołowinę zrumień z kuminem i papryką.', 'W misce ułóż ciepły ryż, fasolę, kukurydzę, mięso i pomidora.', 'Dodaj awokado i jogurt, skrop limonką.']::text[]),
  ('h03', 'Quesadilla z kurczakiem', array['family-favs', 'fakeway']::text[], array['gluten', 'lactose']::text[], array['chicken']::text[], array['stove']::text[], array['mexican']::text[], '{}'::text[], '', 1, 30, 610, 50, 24, 48, array['Usmaż kurczaka z papryką i cebulą.', 'Na tortillę połóż farsz i cheddar, przykryj drugą i opiecz z obu stron, aż ser się stopi.', 'Podawaj z salsą.']::text[]),
  ('h04', 'Chili z indyka i fasoli', array['protein-packed', 'home-style', 'low-calories', 'gut-friendly']::text[], '{}'::text[], array['chicken']::text[], array['stove']::text[], array['mexican']::text[], '{}'::text[], '', 1, 25, 520, 50, 16, 42, array['Podsmaż cebulę, paprykę i czosnek. Dodaj indyka i zrumień.', 'Wlej pomidory, dodaj fasolę i przyprawy. Duś 20–25 minut, aż zgęstnieje.']::text[]),
  ('h05', 'Kurczak z ryżem po meksykańsku', array['family-favs', 'speedy-meals']::text[], '{}'::text[], array['chicken']::text[], array['stove']::text[], array['mexican']::text[], '{}'::text[], '', 1, 7, 610, 48, 14, 66, array['Zrumień kawałki kurczaka. Dodaj cebulę i paprykę, potem pomidory i przyprawy.', 'Wmieszaj ugotowany ryż i kukurydzę, grzej 5–7 minut.']::text[]),
  ('h06', 'Miska fajita z wołowiną', array['protein-packed', 'speedy-meals']::text[], '{}'::text[], array['beef']::text[], array['stove']::text[], array['mexican']::text[], '{}'::text[], '', 1, 30, 650, 45, 23, 61, array['Wołowinę szybko obsmaż na dużym ogniu.', 'Dodaj paprykę i cebulę i smaż, aż lekko się przypalą.', 'Podawaj na ryżu z awokado i limonką.']::text[]),
  ('h07', 'Zapiekanka enchilada z kurczakiem', array['family-favs', 'fakeway', 'speedy-meals', 'gut-friendly']::text[], array['gluten', 'lactose']::text[], array['chicken']::text[], array['oven']::text[], array['mexican']::text[], '{}'::text[], '', 1, 20, 650, 55, 21, 51, array['Ugotowanego kurczaka, fasolę i cebulę zawiń w tortille.', 'Ułóż w naczyniu, polej sosem i posyp cheddarem.', 'Piecz 20 minut w 190°C, na wierzch daj jogurt.']::text[]),
  ('h08', 'Wrap z tuńczykiem i kukurydzą', array['speedy-meals', 'low-calories', 'fakeway']::text[], array['gluten', 'lactose', 'fish']::text[], array['fish']::text[], '{}'::text[], array['mexican']::text[], array['pescatarian']::text[], '', 1, 30, 390, 35, 8, 43, array['Tuńczyka wymieszaj z jogurtem, limonką i pieprzem.', 'Rozsmaruj na wrapie, dodaj kukurydzę, pomidora i sałatę.', 'Zwiń ciasno i przekrój.']::text[]),
  ('h09', 'Tacos z batatem i czarną fasolą', array['healthy-comfort', 'gut-friendly', 'low-calories']::text[], array['gluten']::text[], array['veg']::text[], array['oven']::text[], array['mexican']::text[], array['vegan', 'vegetarian', 'pescatarian']::text[], '', 1, 30, 560, 17, 17, 79, array['Batata pokrój w kostkę i piecz 25–30 minut w 200°C z kuminem.', 'Podgrzej tortille i nałóż batata, fasolę, awokado, pomidora i cebulę.']::text[]),
  ('h10', 'Miska nachos z kurczakiem', array['fakeway', 'family-favs', 'gut-friendly']::text[], array['lactose']::text[], array['chicken']::text[], array['stove']::text[], array['mexican']::text[], '{}'::text[], '', 1, 30, 690, 49, 23, 68, array['Usmaż i pokrój kurczaka.', 'W misce ułóż ryż, fasolę, kukurydzę i kurczaka.', 'Dodaj pokruszone chipsy, ser, salsę i awokado.']::text[]),
  ('h11', 'Makaron z kurczakiem w kremowym sosie pomidorowym', array['home-style', 'family-favs', 'speedy-meals']::text[], array['gluten', 'lactose']::text[], array['chicken']::text[], array['stove']::text[], array['italian']::text[], '{}'::text[], '', 1, 5, 650, 52, 18, 69, array['Ugotuj makaron. Kurczaka zrumień z czosnkiem, dodaj passatę i śmietankę, duś 5 minut.', 'Wymieszaj z makaronem i parmezanem.']::text[]),
  ('h12', 'Spaghetti bolognese', array['family-favs', 'home-style', 'speedy-meals']::text[], array['gluten', 'lactose']::text[], array['beef']::text[], array['stove']::text[], array['italian']::text[], '{}'::text[], '', 1, 20, 700, 47, 20, 78, array['Podsmaż cebulę i marchewkę, dodaj wołowinę i zrumień.', 'Wlej passatę i duś 20 minut.', 'Ugotuj spaghetti, wymieszaj z sosem i posyp parmezanem.']::text[]),
  ('h13', 'Makaron z kurczakiem i pesto', array['speedy-meals', 'protein-packed']::text[], array['gluten', 'lactose']::text[], array['chicken']::text[], array['stove']::text[], array['italian']::text[], '{}'::text[], '', 1, 30, 670, 55, 22, 65, array['Ugotuj makaron i zostaw odrobinę wody z gotowania. Kurczaka usmaż na patelni.', 'Makaron wymieszaj z pesto, pomidorami, szpinakiem i wodą z makaronu. Dodaj kurczaka i parmezan.']::text[]),
  ('h14', 'Makaron z tuńczykiem i pomidorami', array['speedy-meals', 'protein-packed', 'low-calories']::text[], array['gluten', 'fish']::text[], array['fish']::text[], array['stove']::text[], array['italian']::text[], array['pescatarian']::text[], '', 1, 5, 560, 38, 10, 73, array['Ugotuj makaron. Czosnek i pomidory podsmaż, dodaj passatę i odsączonego tuńczyka.', 'Duś 5 minut, wymieszaj z makaronem i pietruszką.']::text[]),
  ('h15', 'Makaron z kiełbasą i pomidorami z jednej patelni', array['home-style', 'speedy-meals']::text[], array['gluten', 'lactose']::text[], array['chicken']::text[], array['stove']::text[], array['italian']::text[], '{}'::text[], '', 1, 30, 680, 36, 25, 71, array['Kiełbasę i cebulę zrumień na dużej patelni.', 'Dodaj pomidory, makaron i tyle wody, żeby makaron się ugotował.', 'Gotuj do miękkości, wmieszaj szpinak i mozzarellę.']::text[]),
  ('h16', 'Zapiekanka z makaronem, szpinakiem i ricottą', array['healthy-comfort', 'family-favs', 'speedy-meals']::text[], array['gluten', 'lactose']::text[], array['veg']::text[], array['stove', 'oven']::text[], array['italian']::text[], array['vegetarian', 'pescatarian']::text[], '', 1, 20, 650, 33, 23, 72, array['Makaron ugotuj prawie al dente. Wymieszaj z ricottą, szpinakiem, czosnkiem i passatą.', 'Przełóż do naczynia, posyp mozzarellą i parmezanem. Piecz 20 minut w 190°C.']::text[]),
  ('h17', 'Makaron z kurczakiem, czosnkiem i brokułami', array['protein-packed', 'healthy-comfort']::text[], array['gluten', 'lactose']::text[], array['chicken']::text[], array['stove']::text[], array['italian']::text[], '{}'::text[], '', 1, 30, 640, 57, 18, 62, array['Ugotuj makaron i brokuły. Kurczaka obsmaż z czosnkiem i oliwą.', 'Wymieszaj makaron i brokuły z kurczakiem, sokiem z cytryny i parmezanem.']::text[]),
  ('h18', 'Gnocchi z pomidorami i mozzarellą', array['home-style', 'speedy-meals']::text[], array['gluten', 'lactose']::text[], array['veg']::text[], array['stove']::text[], array['italian']::text[], array['vegetarian', 'pescatarian']::text[], '', 1, 7, 620, 24, 22, 79, array['Gnocchi podsmaż na patelni, aż się zezłocą.', 'Dodaj czosnek, pomidory i passatę, duś 5–7 minut.', 'Wmieszaj mozzarellę i bazylię, aż ser zmięknie.']::text[]),
  ('h19', 'Makaron z tuńczykiem po śródziemnomorsku', array['low-calories', 'protein-packed']::text[], array['gluten', 'lactose', 'fish']::text[], array['fish']::text[], array['stove']::text[], array['italian']::text[], array['pescatarian']::text[], '', 1, 30, 570, 39, 18, 65, array['Makaron ugotuj i lekko ostudź.', 'Wymieszaj z tuńczykiem, warzywami, oliwkami i fetą.', 'Skrop sokiem z cytryny i oliwą.']::text[]),
  ('h20', 'Makaron z kurczakiem arrabbiata', array['speedy-meals', 'protein-packed']::text[], array['gluten', 'lactose']::text[], array['chicken']::text[], array['stove']::text[], array['italian']::text[], '{}'::text[], '', 1, 8, 620, 52, 15, 69, array['Ugotuj makaron. Kurczaka obsmaż z czosnkiem i chili.', 'Dodaj passatę i duś 8 minut. Wymieszaj z makaronem i parmezanem.']::text[]),
  ('h21', 'Makaron z kurczakiem i pieczarkami w śmietanie', array['home-style', 'family-favs']::text[], array['gluten', 'lactose']::text[], array['chicken']::text[], array['stove']::text[], array['italian']::text[], '{}'::text[], '', 1, 30, 680, 54, 22, 67, array['Ugotuj makaron. Pieczarki i kurczaka podsmaż z czosnkiem.', 'Dodaj śmietankę i parmezan, chwilę pogotuj. Wymieszaj z makaronem.']::text[]),
  ('h22', 'Kurczak z białą fasolą z patelni', array['protein-packed', 'gut-friendly', 'speedy-meals', 'low-calories']::text[], '{}'::text[], array['chicken']::text[], array['stove']::text[], array['italian']::text[], '{}'::text[], '', 1, 15, 500, 54, 14, 38, array['Kurczaka i cebulę zrumień. Dodaj pomidory, fasolę i zioła, duś 12–15 minut.', 'Na końcu wmieszaj szpinak.']::text[]),
  ('h23', 'Klopsiki z indyka w sosie pomidorowym', array['protein-packed', 'family-favs', 'speedy-meals', 'low-calories']::text[], array['gluten', 'lactose', 'eggs']::text[], array['chicken']::text[], array['stove']::text[], array['italian']::text[], '{}'::text[], '', 1, 20, 540, 51, 22, 34, array['Indyka wymieszaj z jajkiem, bułką tartą i przyprawami, uformuj klopsiki.', 'Zrumień na patelni, zalej passatą i duś pod przykryciem 15–20 minut.', 'Posyp parmezanem.']::text[]),
  ('h24', 'Kurczak caprese', array['healthy-comfort', 'low-calories']::text[], array['lactose']::text[], array['chicken']::text[], array['stove']::text[], array['italian']::text[], '{}'::text[], '', 1, 30, 490, 58, 21, 13, array['Kurczaka przypraw i obsmaż. Na wierzch połóż mozzarellę i pomidory, przykryj, aż ser zmięknie.', 'Podawaj z bazylią, sałatą i glazurą balsamiczną.']::text[]),
  ('h25', 'Makaron z kurczakiem, cytryną i czosnkiem', array['speedy-meals', 'healthy-comfort']::text[], array['gluten', 'lactose']::text[], array['chicken']::text[], array['stove']::text[], array['italian']::text[], '{}'::text[], '', 1, 30, 650, 52, 19, 67, array['Ugotuj spaghetti. Kurczaka obsmaż z czosnkiem.', 'Makaron wymieszaj z sokiem i skórką z cytryny, oliwą i parmezanem, dolej odrobinę wody z makaronu.', 'Na wierzch połóż kurczaka i pietruszkę.']::text[]),
  ('h26', 'Kurczak maślany z ryżem', array['fakeway', 'family-favs']::text[], array['lactose']::text[], array['chicken']::text[], array['stove']::text[], array['indian']::text[], '{}'::text[], '', 1, 30, 680, 55, 21, 61, array['Cebulę i przyprawy podsmaż na maśle. Dodaj kurczaka i zrumień, potem passatę i duś.', 'Jogurt wmieszaj już poza ogniem. Podawaj z ryżem.']::text[]),
  ('h27', 'Kurczak tikka masala', array['fakeway', 'protein-packed', 'speedy-meals']::text[], array['lactose']::text[], array['chicken']::text[], array['stove']::text[], array['indian']::text[], '{}'::text[], '', 1, 15, 650, 57, 15, 62, array['Kurczaka zamarynuj 15 minut w jogurcie i przyprawach. Obsmaż do rumieńca.', 'Duś z cebulą i sosem pomidorowym 15 minut. Podawaj z ryżem.']::text[]),
  ('h28', 'Curry z kurczakiem i mlekiem kokosowym', array['home-style', 'protein-packed', 'speedy-meals']::text[], '{}'::text[], array['chicken']::text[], array['stove']::text[], array['indian']::text[], '{}'::text[], '', 1, 15, 650, 49, 22, 60, array['Kurczaka usmaż z cebulą i papryką.', 'Dodaj curry i mleko kokosowe, duś 12–15 minut.', 'Skrop limonką i podawaj z ryżem.']::text[]),
  ('h29', 'Curry z ciecierzycą i szpinakiem', array['gut-friendly', 'healthy-comfort', 'speedy-meals', 'low-calories']::text[], '{}'::text[], array['veg']::text[], array['stove']::text[], array['indian']::text[], array['vegan', 'vegetarian', 'pescatarian']::text[], '', 1, 15, 520, 18, 19, 65, array['Cebulę i czosnek podsmaż z curry.', 'Dodaj pomidory, ciecierzycę i mleko kokosowe, duś 15 minut.', 'Wmieszaj szpinak, aż zwiędnie.']::text[]),
  ('h30', 'Dal z soczewicy z ryżem', array['gut-friendly', 'low-calories', 'speedy-meals']::text[], '{}'::text[], array['veg']::text[], array['stove']::text[], array['indian']::text[], array['vegan', 'vegetarian', 'pescatarian']::text[], '', 1, 20, 560, 25, 9, 91, array['Soczewicę opłucz. Cebulę i przyprawy podsmaż, dodaj soczewicę, pomidory i wodę.', 'Duś 18–20 minut, aż będzie kremowa. Podawaj z ryżem.']::text[]),
  ('h31', 'Curry z kurczaka i pieczone warzywa', array['protein-packed', 'healthy-comfort']::text[], array['lactose']::text[], array['chicken']::text[], array['stove', 'oven']::text[], array['indian']::text[], '{}'::text[], '', 1, 30, 570, 52, 17, 53, array['Ziemniaki i warzywa pokrój i piecz 25–30 minut w 200°C.', 'Kurczaka usmaż z przyprawami na patelni. Podawaj razem z jogurtem.']::text[]),
  ('h32', 'Curry z soczewicy i pomidorów', array['gut-friendly', 'speedy-meals', 'low-calories']::text[], '{}'::text[], array['veg']::text[], array['stove']::text[], array['indian']::text[], array['vegan', 'vegetarian', 'pescatarian']::text[], '', 1, 20, 450, 27, 9, 67, array['Cebulę, czosnek i przyprawy podsmaż.', 'Dodaj soczewicę, passatę i wodę, duś 18–20 minut.', 'Na końcu wmieszaj szpinak.']::text[]),
  ('h33', 'Curry z kurczakiem i ziemniakami', array['family-favs', 'home-style']::text[], '{}'::text[], array['chicken']::text[], array['stove']::text[], array['indian']::text[], '{}'::text[], '', 1, 25, 590, 51, 13, 64, array['Kurczaka i cebulę zrumień.', 'Dodaj ziemniaki, pomidory, groszek, curry i tyle wody, żeby prawie przykryła.', 'Duś 25 minut, aż ziemniaki zmiękną.']::text[]),
  ('h34', 'Miska ryżu z ciecierzycą', array['healthy-comfort', 'low-calories', 'gut-friendly']::text[], array['lactose']::text[], array['veg']::text[], array['stove']::text[], array['indian']::text[], array['vegetarian', 'pescatarian']::text[], '', 1, 30, 540, 19, 15, 80, array['Ciecierzycę podgrzej na patelni z curry.', 'Podawaj na ryżu z ogórkiem, pomidorem i szpinakiem.', 'Na wierzch daj jogurt.']::text[]),
  ('h35', 'Wrap tikka z kurczakiem', array['speedy-meals', 'protein-packed', 'low-calories', 'fakeway']::text[], array['gluten', 'lactose']::text[], array['chicken']::text[], array['stove']::text[], array['indian']::text[], '{}'::text[], '', 1, 30, 470, 48, 10, 48, array['Kurczaka obtocz w jogurcie i przyprawach, usmaż do gotowości.', 'Pokrój i włóż do wrapa z ogórkiem, pomidorem i sałatą. Zwiń ciasno.']::text[]),
  ('h36', 'Dal z soczewicy i mlekiem kokosowym', array['gut-friendly', 'home-style', 'speedy-meals', 'low-calories']::text[], '{}'::text[], array['veg']::text[], array['stove']::text[], array['indian']::text[], array['vegan', 'vegetarian', 'pescatarian']::text[], '', 1, 20, 510, 25, 16, 67, array['Cebulę, czosnek i przyprawy podsmaż.', 'Dodaj soczewicę, mleko kokosowe i wodę, duś 20 minut, aż zgęstnieje.', 'Przed podaniem wmieszaj szpinak.']::text[]),
  ('h37', 'Curry z jajek i pomidorów', array['protein-packed', 'speedy-meals', 'low-calories', 'gut-friendly']::text[], array['eggs']::text[], array['veg']::text[], array['stove']::text[], array['indian']::text[], array['vegetarian', 'pescatarian']::text[], '', 1, 8, 430, 28, 21, 31, array['Cebulę i przyprawy podsmaż, dodaj pomidory i ciecierzycę, duś 8 minut.', 'Zrób wgłębienia, wbij jajka, przykryj i gotuj, aż białko się zetnie.', 'Dodaj szpinak.']::text[]),
  ('h38', 'Kurczak korma z ryżem', array['fakeway', 'family-favs', 'speedy-meals']::text[], array['lactose']::text[], array['chicken']::text[], array['stove']::text[], array['indian']::text[], '{}'::text[], '', 1, 10, 700, 57, 23, 66, array['Kurczaka usmaż z cebulą i przyprawami. Dodaj passatę i duś 10 minut.', 'Zmniejsz ogień i wmieszaj jogurt.', 'Podawaj z ryżem i posiekanymi nerkowcami.']::text[]),
  ('h39', 'Klopsiki z indyka w sosie curry', array['protein-packed', 'fakeway', 'speedy-meals']::text[], array['gluten', 'eggs']::text[], array['chicken']::text[], array['stove']::text[], array['indian']::text[], '{}'::text[], '', 1, 15, 600, 49, 24, 35, array['Indyka wymieszaj z jajkiem i bułką tartą, uformuj klopsiki i zrumień.', 'Dodaj cebulę, curry, passatę i mleko kokosowe. Duś 15 minut.']::text[]),
  ('h40', 'Warzywne curry z ciecierzycą', array['healthy-comfort', 'gut-friendly', 'speedy-meals', 'low-calories']::text[], '{}'::text[], array['veg']::text[], array['stove']::text[], array['indian']::text[], array['vegan', 'vegetarian', 'pescatarian']::text[], '', 1, 20, 500, 17, 17, 69, array['Warzywa podsmaż z curry.', 'Dodaj pomidory, ciecierzycę i mleko kokosowe.', 'Duś 20 minut, aż warzywa zmiękną.']::text[]),
  ('h41', 'Miska ryżu z kurczakiem teriyaki', array['fakeway', 'protein-packed', 'speedy-meals']::text[], '{}'::text[], array['chicken']::text[], array['stove']::text[], array['asian']::text[], '{}'::text[], '', 1, 5, 610, 50, 13, 72, array['Paski kurczaka obsmaż. Dodaj brokuły i marchewkę, smaż 4–5 minut.', 'Wlej sos teriyaki i wymieszaj.', 'Podawaj na ryżu z sezamem.']::text[]),
  ('h42', 'Wołowina z brokułami', array['fakeway', 'speedy-meals']::text[], array['soy']::text[], array['beef']::text[], array['stove']::text[], array['asian']::text[], '{}'::text[], '', 1, 30, 620, 45, 18, 61, array['Wołowinę lekko obtocz w skrobi i obsmaż na dużym ogniu.', 'Dodaj brokuły, czosnek i imbir.', 'Wlej sos sojowy i odrobinę wody, smaż aż sos się zeszkli. Podawaj z ryżem.']::text[]),
  ('h43', 'Smażony ryż z kurczakiem', array['family-favs', 'speedy-meals']::text[], array['eggs', 'soy']::text[], array['chicken']::text[], array['stove']::text[], array['asian']::text[], '{}'::text[], '', 1, 30, 640, 44, 19, 73, array['Kurczaka usmaż na mocno rozgrzanej patelni. Dodaj marchewkę i groszek, odsuń i usmaż jajecznicę.', 'Dodaj ryż i sos sojowy, smaż aż będzie gorący i lekko chrupiący.']::text[]),
  ('h44', 'Smażony ryż z jajkiem i warzywami', array['speedy-meals', 'low-calories']::text[], array['eggs', 'soy']::text[], array['veg']::text[], array['stove']::text[], array['asian']::text[], array['vegetarian', 'pescatarian']::text[], '', 1, 30, 560, 20, 17, 79, array['Jajka usmaż na rozgrzanej patelni i odłóż.', 'Podsmaż warzywa, dodaj ryż i sos sojowy, wmieszaj jajka i podgrzej.']::text[]),
  ('h45', 'Kurczak w słodkim chili z ryżem', array['fakeway', 'protein-packed', 'speedy-meals']::text[], '{}'::text[], array['chicken']::text[], array['stove']::text[], array['asian']::text[], '{}'::text[], '', 1, 3, 630, 49, 12, 83, array['Kurczaka obsmaż, dodaj paprykę i brokuły.', 'Wlej słodkie chili i smaż 2–3 minuty, aż sos się sklei.', 'Podawaj na ryżu z limonką.']::text[]),
  ('h46', 'Makaron z kurczakiem i czosnkiem', array['speedy-meals', 'family-favs']::text[], array['gluten', 'eggs', 'soy']::text[], array['chicken']::text[], array['stove']::text[], array['asian']::text[], '{}'::text[], '', 1, 3, 610, 48, 14, 67, array['Ugotuj makaron. Kurczaka, czosnek i warzywa smaż na dużym ogniu.', 'Dodaj makaron i sos sojowy, wymieszaj 2–3 minuty.']::text[]),
  ('h47', 'Makaron z wołowiną', array['protein-packed', 'fakeway']::text[], array['gluten', 'eggs', 'soy']::text[], array['beef']::text[], array['stove']::text[], array['asian']::text[], '{}'::text[], '', 1, 30, 680, 48, 20, 71, array['Ugotuj makaron. Wołowinę obsmaż na dużym ogniu, dodaj warzywa.', 'Wlej sosy i makaron, wymieszaj aż wszystko pokryje sos.']::text[]),
  ('h48', 'Kurczak sezamowy z ryżem', array['fakeway', 'family-favs']::text[], array['soy']::text[], array['chicken']::text[], array['stove']::text[], array['asian']::text[], '{}'::text[], '', 1, 30, 650, 51, 15, 75, array['Wymieszaj sos sojowy, miód, czosnek i imbir.', 'Kurczaka usmaż do rumieńca, dodaj sos i brokuły, redukuj aż się zeszkli.', 'Podawaj z ryżem i sezamem.']::text[]),
  ('h49', 'Makaron z kurczakiem i masłem orzechowym', array['protein-packed', 'fakeway']::text[], array['gluten', 'eggs', 'soy']::text[], array['chicken']::text[], array['stove']::text[], array['asian']::text[], '{}'::text[], '', 1, 30, 690, 48, 22, 71, array['Ugotuj makaron i kurczaka.', 'Masło orzechowe wymieszaj z sosem sojowym, limonką, czosnkiem i odrobiną gorącej wody.', 'Makaron i kurczaka wymieszaj z sosem i warzywami.']::text[]),
  ('h50', 'Ramen z jajkiem i warzywami', array['speedy-meals', 'home-style', 'low-calories']::text[], array['gluten', 'eggs', 'soy']::text[], array['veg']::text[], array['stove']::text[], array['asian']::text[], array['vegetarian', 'pescatarian']::text[], '', 1, 30, 500, 23, 15, 65, array['Bulion z sosem sojowym zagotuj.', 'Dodaj makaron i pieczarki, potem kukurydzę i szpinak.', 'Wbij jajka albo włóż ugotowane. Gotuj, aż makaron zmięknie.']::text[]),
  ('h51', 'Miska ryżu z kurczakiem i imbirem', array['healthy-comfort', 'protein-packed']::text[], array['soy']::text[], array['chicken']::text[], array['stove']::text[], array['asian']::text[], '{}'::text[], '', 1, 30, 600, 51, 13, 69, array['Kurczaka obsmaż z imbirem.', 'Dodaj warzywa i smaż, aż będą chrupiąco-miękkie.', 'Wlej sos sojowy i podawaj na ryżu ze szczypiorkiem.']::text[]),
  ('h52', 'Kurczak z miodem i czosnkiem', array['fakeway', 'family-favs']::text[], array['soy']::text[], array['chicken']::text[], array['stove']::text[], array['asian']::text[], '{}'::text[], '', 1, 30, 630, 51, 14, 76, array['Kurczaka usmaż do rumieńca.', 'Dodaj warzywa, potem miód, sos sojowy i czosnek.', 'Smaż, aż sos pokryje wszystko. Podawaj z ryżem.']::text[]),
  ('h53', 'Ostra miska ryżu z wołowiną', array['protein-packed', 'speedy-meals']::text[], array['soy']::text[], array['beef']::text[], array['stove']::text[], array['asian']::text[], '{}'::text[], '', 1, 30, 650, 46, 19, 74, array['Wołowinę obsmaż z gochujang i sosem sojowym.', 'Podawaj na ryżu z ogórkiem, marchewką i szczypiorkiem.', 'Posyp sezamem.']::text[]),
  ('h54', 'Łosoś teriyaki z ryżem', array['protein-packed', 'healthy-comfort']::text[], array['fish']::text[], array['fish']::text[], array['stove']::text[], array['asian']::text[], array['pescatarian']::text[], '', 1, 30, 680, 43, 24, 67, array['Łososia upiecz albo obsmaż, żeby został lekko różowy w środku.', 'Brokuły ugotuj na parze albo na patelni.', 'Posmaruj łososia teriyaki i podawaj z ryżem i sezamem.']::text[]),
  ('h55', 'Udon z kurczakiem i warzywami', array['family-favs', 'speedy-meals']::text[], array['gluten', 'soy']::text[], array['chicken']::text[], array['stove']::text[], array['asian']::text[], '{}'::text[], '', 1, 30, 610, 44, 12, 75, array['Kurczaka podsmaż z czosnkiem i imbirem.', 'Dodaj warzywa i smaż, aż będą chrupiąco-miękkie.', 'Dodaj udon i sos sojowy, wymieszaj aż będzie gorące.']::text[]),
  ('h56', 'Miska z kurczakiem po śródziemnomorsku', array['healthy-comfort', 'protein-packed', 'gut-friendly']::text[], array['lactose']::text[], array['chicken']::text[], array['stove']::text[], array['mediterranean']::text[], '{}'::text[], '', 1, 30, 650, 52, 23, 60, array['Kurczaka usmaż i pokrój.', 'W misce ułóż komosę, ciecierzycę, ogórka, pomidora i fetę.', 'Skrop cytryną i oliwą.']::text[]),
  ('h57', 'Kurczak po grecku z ziemniakami', array['family-favs', 'healthy-comfort']::text[], '{}'::text[], array['chicken']::text[], array['oven']::text[], array['mediterranean']::text[], '{}'::text[], '', 1, 35, 650, 47, 24, 55, array['Kurczaka i ziemniaczane ćwiartki wymieszaj z cytryną, czosnkiem, oregano i oliwą.', 'Piecz 30–35 minut w 200°C, aż się zrumienią i kurczak będzie gotowy.', 'Podawaj z ogórkiem.']::text[]),
  ('h58', 'Sałatka grecka z kurczakiem i fetą', array['low-calories', 'protein-packed']::text[], array['lactose']::text[], array['chicken']::text[], array['stove']::text[], array['mediterranean']::text[], '{}'::text[], '', 1, 30, 480, 52, 24, 17, array['Kurczaka usmaż na patelni albo grillu i pokrój.', 'Warzywa wymieszaj z fetą i oliwkami.', 'Dodaj kurczaka, skrop cytryną i oliwą.']::text[]),
  ('h59', 'Sałatka z tuńczyka i białej fasoli', array['protein-packed', 'gut-friendly', 'low-calories']::text[], array['fish']::text[], array['fish']::text[], '{}'::text[], array['mediterranean']::text[], array['pescatarian']::text[], '', 1, 30, 430, 40, 14, 38, array['Tuńczyka i fasolę odsącz.', 'Wymieszaj z pomidorem, cebulą i pietruszką.', 'Skrop cytryną i oliwą, podawaj schłodzone.']::text[]),
  ('h60', 'Miska z ciecierzycą po śródziemnomorsku', array['gut-friendly', 'healthy-comfort']::text[], array['lactose']::text[], array['veg']::text[], array['stove']::text[], array['mediterranean']::text[], array['vegetarian', 'pescatarian']::text[], '', 1, 30, 590, 20, 22, 78, array['Komosę, ciecierzycę i warzywa wymieszaj.', 'Dodaj fetę, skrop cytryną i oliwą.', 'Podawaj w temperaturze pokojowej.']::text[]),
  ('h61', 'Łosoś z cytryną, czosnkiem i warzywami', array['low-calories', 'protein-packed', 'speedy-meals']::text[], array['fish']::text[], array['fish']::text[], array['oven']::text[], array['mediterranean']::text[], array['pescatarian']::text[], '', 1, 20, 540, 42, 30, 24, array['Łososia i warzywa ułóż na blasze.', 'Przypraw czosnkiem, cytryną i oliwą.', 'Piecz 15–20 minut w 200°C, aż łosoś się rozdziela, a warzywa zmiękną.']::text[]),
  ('h62', 'Souvlaki z kurczaka z ryżem', array['fakeway', 'protein-packed']::text[], array['gluten', 'lactose']::text[], array['chicken']::text[], array['stove']::text[], array['mediterranean']::text[], '{}'::text[], '', 1, 30, 650, 57, 16, 72, array['Kurczaka przypraw oregano i cytryną, usmaż do rumieńca.', 'Pokrój i podawaj z ryżem, pitą, ogórkiem, pomidorem i jogurtem z czosnkiem.']::text[]),
  ('h63', 'Klopsiki z indyka z tzatziki', array['protein-packed', 'fakeway', 'speedy-meals', 'low-calories']::text[], array['gluten', 'lactose', 'eggs']::text[], array['chicken']::text[], array['oven']::text[], array['mediterranean']::text[], '{}'::text[], '', 1, 20, 540, 50, 21, 34, array['Indyka wymieszaj z jajkiem i bułką tartą, uformuj klopsiki.', 'Piecz 18–20 minut w 200°C.', 'Jogurt wymieszaj z ogórkiem, czosnkiem i koperkiem i podawaj obok.']::text[]),
  ('h64', 'Sałatka makaronowa po śródziemnomorsku', array['low-calories', 'speedy-meals']::text[], array['gluten', 'lactose']::text[], array['veg']::text[], array['stove']::text[], array['mediterranean']::text[], array['vegetarian', 'pescatarian']::text[], '', 1, 30, 560, 20, 22, 67, array['Makaron ugotuj i lekko ostudź.', 'Wymieszaj z warzywami, oliwkami i fetą.', 'Skrop cytryną i oliwą.']::text[]),
  ('h65', 'Makaron z pieczoną fetą i pomidorami', array['home-style', 'speedy-meals']::text[], array['gluten', 'lactose']::text[], array['veg']::text[], array['stove', 'oven']::text[], array['mediterranean']::text[], array['vegetarian', 'pescatarian']::text[], '', 1, 20, 650, 24, 25, 77, array['Fetę i pomidory włóż do naczynia z czosnkiem i oliwą. Piecz 20 minut w 200°C.', 'Ugotuj makaron i wymieszaj z upieczoną fetą oraz szpinakiem.']::text[]),
  ('h66', 'Miska z tuńczykiem i jajkiem', array['protein-packed', 'low-calories']::text[], array['lactose', 'eggs', 'fish']::text[], array['fish']::text[], array['stove']::text[], array['mediterranean']::text[], array['pescatarian']::text[], '', 1, 30, 560, 43, 23, 41, array['Jajka ugotuj i ostudź.', 'Komosę, tuńczyka i warzywa wymieszaj.', 'Na wierzch połóż jajka, oliwki i fetę, skrop oliwą.']::text[]),
  ('h67', 'Kuskus z pieczonymi warzywami i fetą', array['healthy-comfort', 'gut-friendly', 'low-calories']::text[], array['gluten', 'lactose']::text[], array['veg']::text[], array['oven']::text[], array['mediterranean']::text[], array['vegetarian', 'pescatarian']::text[], '', 1, 25, 560, 18, 21, 75, array['Warzywa pokrój i piecz 20–25 minut w 200°C.', 'Kuskus zalej wrzątkiem.', 'Wymieszaj i posyp fetą oraz ziołami.']::text[]),
  ('h68', 'Kuskus z kurczakiem i cytryną', array['speedy-meals', 'protein-packed', 'gut-friendly']::text[], array['gluten']::text[], array['chicken']::text[], array['stove']::text[], array['mediterranean']::text[], '{}'::text[], '', 1, 30, 590, 48, 16, 65, array['Kurczaka i cukinię usmaż na patelni z cytryną i ziołami.', 'Kuskus zalej wrzątkiem.', 'Wymieszaj kuskus z ciecierzycą i połóż na wierzchu kurczaka.']::text[]),
  ('h69', 'Faszerowana papryka po grecku', array['family-favs', 'healthy-comfort', 'low-calories']::text[], array['lactose']::text[], array['chicken']::text[], array['stove', 'oven']::text[], array['mediterranean']::text[], '{}'::text[], '', 1, 35, 540, 45, 18, 52, array['Indyka i cebulę podsmaż, wymieszaj z ryżem, pomidorem i oregano.', 'Napełnij papryki, posyp fetą.', 'Piecz 30–35 minut w 190°C.']::text[]),
  ('h70', 'Gulasz z kurczaka i ciecierzycy', array['gut-friendly', 'home-style']::text[], '{}'::text[], array['chicken']::text[], array['stove']::text[], array['mediterranean']::text[], '{}'::text[], '', 1, 30, 590, 51, 15, 63, array['Kurczaka i cebulę zrumień.', 'Dodaj ziemniaki, marchewkę, ciecierzycę, pomidory i wodę.', 'Duś 25–30 minut, aż warzywa zmiękną.']::text[]),
  ('h71', 'Kotlet z kurczaka z ziemniakami', array['family-favs', 'home-style']::text[], array['gluten', 'eggs']::text[], array['chicken']::text[], array['stove']::text[], array['polish']::text[], '{}'::text[], '', 1, 30, 680, 55, 24, 63, array['Kurczaka rozbij i przypraw. Obtocz w mące, jajku i bułce tartej.', 'Smaż na oleju, aż będzie złoty i gotowy w środku.', 'Podawaj z ugotowanymi albo upieczonymi ziemniakami.']::text[]),
  ('h72', 'Rosół z kurczaka', array['home-style', 'gut-friendly', 'low-calories']::text[], '{}'::text[], array['chicken']::text[], array['stove']::text[], array['polish']::text[], '{}'::text[], '', 1, 30, 420, 45, 8, 42, array['Kurczaka, warzywa i liść laurowy włóż do bulionu.', 'Gotuj 25–30 minut, aż kurczak i ziemniaki zmiękną.', 'Kurczaka wyjmij, rozdrobnij i włóż z powrotem. Posyp pietruszką.']::text[]),
  ('h73', 'Zupa pomidorowa z ryżem', array['home-style', 'low-calories', 'speedy-meals']::text[], array['lactose']::text[], array['veg']::text[], array['stove', 'blender']::text[], array['polish']::text[], array['vegetarian', 'pescatarian']::text[], '', 1, 20, 350, 10, 9, 55, array['Cebulę i marchewkę podsmaż. Dodaj pomidory i bulion, gotuj 20 minut.', 'Zblenduj na gładko, wmieszaj ryż.', 'Podawaj z jogurtem.']::text[]),
  ('h74', 'Placki ziemniaczane', array['home-style', 'family-favs']::text[], array['lactose', 'eggs']::text[], array['veg']::text[], array['stove']::text[], array['polish']::text[], array['vegetarian', 'pescatarian']::text[], '', 1, 30, 590, 17, 24, 76, array['Ziemniaki zetrzyj i odciśnij wodę.', 'Wymieszaj z jajkiem, cebulą i mąką.', 'Smaż łyżki ciasta na oleju, aż będą chrupiące z obu stron. Podawaj z jogurtem i koperkiem.']::text[]),
  ('h75', 'Zupa z kurczakiem i pęczakiem', array['gut-friendly', 'healthy-comfort', 'speedy-meals', 'low-calories']::text[], '{}'::text[], array['chicken']::text[], array['stove']::text[], array['polish']::text[], '{}'::text[], '', 1, 20, 470, 43, 8, 60, array['Pęczak ugotuj prawie do miękkości.', 'Cebulę, marchewkę i seler podsmaż, dodaj bulion, pęczak i kurczaka.', 'Gotuj 20 minut, kurczaka rozdrobnij i posyp pietruszką.']::text[]),
  ('h76', 'Kurczak z kapustą z jednego garnka', array['healthy-comfort', 'family-favs']::text[], '{}'::text[], array['chicken']::text[], array['stove']::text[], array['polish']::text[], '{}'::text[], '', 1, 30, 570, 45, 17, 57, array['Kurczaka i cebulę zrumień w garnku.', 'Dodaj kapustę, ziemniaki, marchewkę, pomidory i paprykę.', 'Dolej trochę wody i duś pod przykryciem 30 minut.']::text[]),
  ('h77', 'Klopsiki z indyka i ziemniaki z koperkiem', array['protein-packed', 'family-favs']::text[], array['gluten', 'lactose', 'eggs']::text[], array['chicken']::text[], array['stove']::text[], array['polish']::text[], '{}'::text[], '', 1, 30, 610, 49, 20, 57, array['Indyka wymieszaj z jajkiem i bułką tartą, uformuj klopsiki i usmaż.', 'Ziemniaki ugotuj, wymieszaj z koperkiem i jogurtem.', 'Podawaj razem.']::text[]),
  ('h78', 'Kurczak z kaszą gryczaną', array['healthy-comfort', 'protein-packed', 'low-calories']::text[], '{}'::text[], array['chicken']::text[], array['stove']::text[], array['polish']::text[], '{}'::text[], '', 1, 30, 520, 50, 12, 51, array['Ugotuj kaszę. Cebulę i marchewkę podsmaż, dodaj kurczaka i paprykę, smaż do gotowości.', 'Podawaj na kaszy ze świeżym ogórkiem.']::text[]),
  ('h79', 'Kurczak pieczony z kiszoną kapustą', array['gut-friendly', 'home-style']::text[], '{}'::text[], array['chicken']::text[], array['oven']::text[], array['polish']::text[], '{}'::text[], '', 1, 40, 570, 46, 18, 54, array['Kiszoną kapustę, jabłko, cebulę i ziemniaki ułóż w naczyniu.', 'Przypraw kminkiem, połóż kurczaka na wierzchu.', 'Piecz pod przykryciem 40 minut w 190°C, na końcu na chwilę odkryj.']::text[]),
  ('h80', 'Ziemniaki z jajkiem i koperkiem', array['speedy-meals', 'home-style', 'low-calories']::text[], array['lactose', 'eggs']::text[], array['veg']::text[], array['stove']::text[], array['polish']::text[], array['vegetarian', 'pescatarian']::text[], '', 1, 30, 500, 24, 21, 55, array['Ziemniaki i cebulę pokrój i smaż, aż będą złote i miękkie.', 'Wlej roztrzepane jajka i smaż, aż się zetną.', 'Posyp koperkiem i podawaj z ogórkiem.']::text[]),
  ('h81', 'Leczo z kurczakiem', array['healthy-comfort', 'family-favs', 'speedy-meals', 'low-calories', 'gut-friendly']::text[], '{}'::text[], array['chicken']::text[], array['stove']::text[], array['polish']::text[], '{}'::text[], '', 1, 20, 500, 48, 12, 47, array['Kurczaka i cebulę podsmaż.', 'Dodaj cukinię i paprykę, potem pomidory i fasolę.', 'Przypraw papryką w proszku i duś 15–20 minut.']::text[]),
  ('h82', 'Gulasz z indyka i kasza gryczana', array['protein-packed', 'home-style', 'speedy-meals', 'low-calories']::text[], '{}'::text[], array['chicken']::text[], array['stove']::text[], array['polish']::text[], '{}'::text[], '', 1, 15, 540, 48, 16, 50, array['Indyka zrumień z cebulą.', 'Dodaj marchewkę, paprykę, pomidory i paprykę w proszku, duś 15 minut.', 'Podawaj z ugotowaną kaszą.']::text[]),
  ('h83', 'Miska z twarogiem i ziemniakami', array['protein-packed', 'speedy-meals', 'low-calories']::text[], array['lactose']::text[], array['veg']::text[], array['stove']::text[], array['polish']::text[], array['vegetarian', 'pescatarian']::text[], '', 1, 30, 500, 34, 12, 61, array['Ziemniaki ugotuj albo upiecz.', 'Twaróg wymieszaj z jogurtem, koperkiem, solą i pieprzem.', 'Podawaj z ziemniakami, ogórkiem i rzodkiewką.']::text[]),
  ('h84', 'Kasza z pieczarkami i twarogiem', array['gut-friendly', 'healthy-comfort', 'low-calories']::text[], array['lactose']::text[], array['veg']::text[], array['stove']::text[], array['polish']::text[], array['vegetarian', 'pescatarian']::text[], '', 1, 30, 480, 26, 15, 61, array['Pieczarki i cebulę podsmaż.', 'Dodaj ugotowaną kaszę i szpinak, podgrzej.', 'Na wierzch połóż twaróg i koperek.']::text[]),
  ('h85', 'Gołąbki z indykiem', array['family-favs', 'protein-packed', 'low-calories']::text[], array['eggs']::text[], array['chicken']::text[], array['stove', 'oven']::text[], array['polish']::text[], '{}'::text[], '', 1, 45, 560, 49, 17, 51, array['Liście kapusty zblanszuj.', 'Indyka wymieszaj z ryżem, jajkiem i cebulą, zawijaj w liście.', 'Ułóż w passacie, przykryj i piecz 45 minut w 190°C.']::text[]),
  ('h86', 'Pęczak z kurczakiem i pieczarkami', array['home-style', 'healthy-comfort']::text[], array['lactose']::text[], array['chicken']::text[], array['stove']::text[], array['polish']::text[], '{}'::text[], '', 1, 30, 610, 49, 17, 70, array['Kurczaka, pieczarki i cebulę podsmaż.', 'Dodawaj pęczak i bulion partiami, mieszaj około 30 minut, aż pęczak zmięknie.', 'Na końcu wmieszaj parmezan.']::text[]),
  ('h87', 'Indyk z warzywami z patelni', array['low-calories', 'protein-packed', 'speedy-meals']::text[], '{}'::text[], array['chicken']::text[], array['stove']::text[], array['polish']::text[], '{}'::text[], '', 1, 20, 430, 43, 13, 31, array['Indyka zrumień z cebulą.', 'Dodaj warzywa i pomidory.', 'Duś pod przykryciem 15–20 minut, aż warzywa zmiękną.']::text[]),
  ('h88', 'Pieczone ziemniaki z twarogiem', array['protein-packed', 'speedy-meals', 'low-calories']::text[], array['lactose']::text[], array['veg']::text[], array['oven']::text[], array['polish']::text[], array['vegetarian', 'pescatarian']::text[], '', 1, 60, 510, 34, 12, 69, array['Ziemniaki piecz 45–60 minut w 200°C, aż będą miękkie.', 'Rozkrój i napełnij twarogiem wymieszanym z jogurtem i szczypiorkiem.']::text[]),
  ('h89', 'Warzywny gulasz', array['gut-friendly', 'low-calories']::text[], '{}'::text[], array['veg']::text[], array['stove']::text[], array['polish']::text[], array['vegan', 'vegetarian', 'pescatarian']::text[], '', 1, 30, 430, 17, 9, 67, array['Cebulę podsmaż, dodaj pokrojone warzywa i pomidory.', 'Dolej wodę i duś 25–30 minut.', 'Pod koniec wmieszaj fasolę.']::text[]),
  ('h90', 'Kurczak z kiszoną kapustą', array['gut-friendly', 'protein-packed', 'low-calories']::text[], '{}'::text[], array['chicken']::text[], array['stove']::text[], array['polish']::text[], '{}'::text[], '', 1, 25, 530, 48, 13, 54, array['Kurczaka i cebulę zrumień.', 'Dodaj kiszoną kapustę, ziemniaka i jabłko oraz trochę wody.', 'Przykryj i duś 25 minut, przed podaniem wmieszaj musztardę.']::text[]),
  ('h91', 'Burger z kurczakiem i frytkami z piekarnika', array['fakeway', 'family-favs']::text[], array['gluten', 'lactose', 'eggs']::text[], array['chicken']::text[], array['oven']::text[], array['fusion']::text[], '{}'::text[], '', 1, 25, 760, 57, 25, 83, array['Kurczaka obtocz w jajku i bułce tartej.', 'Kurczaka i ziemniaczane ćwiartki piecz 20–25 minut w 210°C, raz obróć.', 'Złóż burgera z sałatą, pomidorem i sosem jogurtowym.']::text[]),
  ('h92', 'Gyros z kurczaka', array['fakeway', 'protein-packed']::text[], array['gluten', 'lactose']::text[], array['chicken']::text[], array['stove']::text[], array['mediterranean']::text[], '{}'::text[], '', 1, 30, 590, 57, 14, 55, array['Kurczaka przypraw papryką, kuminem i czosnkiem, usmaż do rumieńca.', 'Pokrój i napełnij pitę warzywami oraz jogurtem z czosnkiem.']::text[]),
  ('h93', 'Wrap z chrupiącym kurczakiem', array['fakeway', 'speedy-meals']::text[], array['gluten', 'lactose', 'eggs']::text[], array['chicken']::text[], array['stove']::text[], array['fusion']::text[], '{}'::text[], '', 1, 30, 620, 52, 20, 57, array['Paski kurczaka obtocz w jajku i bułce tartej, smaż albo piecz w frytkownicy, aż będą chrupiące.', 'Wrap napełnij sałatą, pomidorem i sosem jogurtowym.']::text[]),
  ('h94', 'Miska cheeseburger z wołowiną', array['fakeway', 'protein-packed']::text[], array['lactose']::text[], array['beef']::text[], array['stove']::text[], array['fusion']::text[], '{}'::text[], '', 1, 30, 700, 45, 27, 63, array['Wołowinę zrumień z cebulą.', 'W misce ułóż ryż, sałatę, pomidora, ogórki i mięso.', 'Na wierzch daj cheddar i sos burgerowy.']::text[]),
  ('h95', 'Wrap Caesar z kurczakiem', array['fakeway', 'speedy-meals']::text[], array['gluten', 'lactose']::text[], array['chicken']::text[], array['stove']::text[], array['italian']::text[], '{}'::text[], '', 1, 30, 590, 53, 17, 52, array['Panierowanego kurczaka usmaż na patelni albo w frytkownicy.', 'Jogurt wymieszaj z cytryną, czosnkiem i parmezanem.', 'Wrap napełnij sałatą, kurczakiem i sosem.']::text[]),
  ('h96', 'Pizza na tortilli', array['fakeway', 'family-favs', 'speedy-meals']::text[], array['gluten', 'lactose']::text[], array['chicken']::text[], array['oven']::text[], array['italian']::text[], '{}'::text[], '', 1, 12, 590, 43, 21, 54, array['Tortillę posmaruj passatą.', 'Nałóż ugotowanego kurczaka, paprykę i mozzarellę.', 'Piecz 8–12 minut w 220°C, aż będzie chrupiąca, a ser się stopi. Posyp oregano.']::text[]),
  ('h97', 'Miska shawarma z kurczakiem', array['fakeway', 'protein-packed']::text[], '{}'::text[], array['chicken']::text[], array['stove']::text[], array['mediterranean']::text[], '{}'::text[], '', 1, 30, 670, 58, 22, 61, array['Kurczaka przypraw, usmaż i pokrój.', 'Do miski włóż ryż, hummus i warzywa.', 'Polej tahini i posyp papryką.']::text[]),
  ('h98', 'Pieczony ziemniak z kurczakiem i serem', array['home-style', 'protein-packed', 'fakeway']::text[], array['lactose']::text[], array['chicken']::text[], array['stove', 'oven']::text[], array['fusion']::text[], '{}'::text[], '', 1, 60, 650, 52, 20, 72, array['Ziemniaka piecz 50–60 minut w 200°C.', 'Kurczaka usmaż i pokrój.', 'Ziemniaka rozkrój, rozluźnij miąższ i napełnij kurczakiem, serem, jogurtem i szczypiorkiem.']::text[]),
  ('h99', 'Ryż z chrupiącym kurczakiem i ostrym majonezem', array['fakeway', 'protein-packed']::text[], array['gluten', 'eggs']::text[], array['chicken']::text[], array['oven']::text[], array['asian']::text[], '{}'::text[], '', 1, 30, 700, 52, 22, 73, array['Kurczaka obtocz w jajku i panko, upiecz w frytkownicy albo w piekarniku, aż będzie chrupiący.', 'Majonez wymieszaj ze srirachą.', 'Podawaj kurczaka na ryżu z ogórkiem i ostrym majonezem.']::text[]),
  ('h100', 'Domowe burrito z kurczakiem', array['fakeway', 'family-favs', 'gut-friendly']::text[], array['gluten', 'lactose']::text[], array['chicken']::text[], array['stove']::text[], array['mexican']::text[], '{}'::text[], '', 1, 30, 760, 58, 24, 82, array['Kurczaka usmaż i pokrój.', 'Na tortillę nałóż ryż, fasolę, kurczaka, ser, salsę, awokado i jogurt.', 'Zwiń ciasno i opiecz na patelni, szwem do dołu.']::text[])
;

insert into recipe_ingredients (recipe_id, product_id, qty_per_person, quantity, unit, is_pantry_ingredient) values
  ('h01', 'kurczak', 0.15, 0.15, 'kg', false),
  ('h01', 'tortilla-kukurydza', 0.5, 0.5, 'opak', false),
  ('h01', 'awokado', 0.375, 0.375, 'szt', false),
  ('h01', 'pomidory', 0.08, 0.08, 'kg', false),
  ('h01', 'cebula', 0.03, 0.03, 'kg', false),
  ('h01', 'limonka', 0.5, 0.5, 'szt', false),
  ('h01', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h02', 'mielone', 0.15, 0.15, 'kg', false),
  ('h02', 'ryz', 0.06, 0.06, 'kg', false),
  ('h02', 'fasola-czarna', 0.417, 0.417, 'szt', false),
  ('h02', 'kukurydza', 0.429, 0.429, 'szt', false),
  ('h02', 'pomidory', 0.08, 0.08, 'kg', false),
  ('h02', 'awokado', 0.313, 0.313, 'szt', false),
  ('h02', 'jogurt-grecki', 0.267, 0.267, 'szt', false),
  ('h02', 'limonka', 0.5, 0.5, 'szt', false),
  ('h03', 'kurczak', 0.14, 0.14, 'kg', false),
  ('h03', 'tortilla', 0.333, 0.333, 'opak', false),
  ('h03', 'cheddar', 0.05, 0.05, 'kg', false),
  ('h03', 'papryka', 0.07, 0.07, 'kg', false),
  ('h03', 'cebula', 0.04, 0.04, 'kg', false),
  ('h03', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h03', 'salsa', 0.2, 0.2, 'szt', false),
  ('h04', 'indyk', 0.18, 0.18, 'kg', false),
  ('h04', 'fasola', 0.5, 0.5, 'szt', false),
  ('h04', 'pomidory-puszka', 0.5, 0.5, 'szt', false),
  ('h04', 'cebula', 0.07, 0.07, 'kg', false),
  ('h04', 'papryka', 0.08, 0.08, 'kg', false),
  ('h04', 'czosnek', 0.12, 0.12, 'szt', false),
  ('h04', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h05', 'kurczak', 0.15, 0.15, 'kg', false),
  ('h05', 'ryz', 0.072, 0.072, 'kg', false),
  ('h05', 'pomidory-puszka', 0.375, 0.375, 'szt', false),
  ('h05', 'papryka', 0.08, 0.08, 'kg', false),
  ('h05', 'cebula', 0.05, 0.05, 'kg', false),
  ('h05', 'kukurydza', 0.429, 0.429, 'szt', false),
  ('h05', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h06', 'wolowina', 0.16, 0.16, 'kg', false),
  ('h06', 'ryz', 0.064, 0.064, 'kg', false),
  ('h06', 'papryka', 0.1, 0.1, 'kg', false),
  ('h06', 'cebula', 0.06, 0.06, 'kg', false),
  ('h06', 'awokado', 0.313, 0.313, 'szt', false),
  ('h06', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h06', 'limonka', 0.5, 0.5, 'szt', false),
  ('h07', 'kurczak', 0.16, 0.16, 'kg', false),
  ('h07', 'tortilla-kukurydza', 0.667, 0.667, 'opak', false),
  ('h07', 'passata', 0.36, 0.36, 'szt', false),
  ('h07', 'cheddar', 0.05, 0.05, 'kg', false),
  ('h07', 'fasola-czarna', 0.333, 0.333, 'szt', false),
  ('h07', 'cebula', 0.04, 0.04, 'kg', false),
  ('h07', 'jogurt-grecki', 0.2, 0.2, 'szt', false),
  ('h08', 'tunczyk', 1, 1, 'szt', false),
  ('h08', 'tortilla', 0.167, 0.167, 'opak', false),
  ('h08', 'kukurydza', 0.429, 0.429, 'szt', false),
  ('h08', 'pomidory', 0.08, 0.08, 'kg', false),
  ('h08', 'salata', 0.25, 0.25, 'szt', false),
  ('h08', 'jogurt-grecki', 0.333, 0.333, 'szt', false),
  ('h08', 'limonka', 0.5, 0.5, 'szt', false),
  ('h09', 'batat', 0.22, 0.22, 'kg', false),
  ('h09', 'fasola-czarna', 0.417, 0.417, 'szt', false),
  ('h09', 'tortilla-kukurydza', 0.5, 0.5, 'opak', false),
  ('h09', 'awokado', 0.313, 0.313, 'szt', false),
  ('h09', 'pomidory', 0.08, 0.08, 'kg', false),
  ('h09', 'cebula', 0.03, 0.03, 'kg', false),
  ('h09', 'limonka', 0.5, 0.5, 'szt', false),
  ('h10', 'kurczak', 0.15, 0.15, 'kg', false),
  ('h10', 'ryz', 0.052, 0.052, 'kg', false),
  ('h10', 'chipsy', 0.233, 0.233, 'szt', false),
  ('h10', 'fasola-czarna', 0.292, 0.292, 'szt', false),
  ('h10', 'kukurydza', 0.357, 0.357, 'szt', false),
  ('h10', 'cheddar', 0.035, 0.035, 'kg', false),
  ('h10', 'salsa', 0.267, 0.267, 'szt', false),
  ('h10', 'awokado', 0.25, 0.25, 'szt', false),
  ('h11', 'kurczak', 0.15, 0.15, 'kg', false),
  ('h11', 'penne', 0.16, 0.16, 'szt', false),
  ('h11', 'passata', 0.36, 0.36, 'szt', false),
  ('h11', 'smietanka', 0.3, 0.3, 'szt', false),
  ('h11', 'parmezan', 0.02, 0.02, 'kg', false),
  ('h11', 'czosnek', 0.12, 0.12, 'szt', false),
  ('h11', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h12', 'mielone', 0.15, 0.15, 'kg', false),
  ('h12', 'spaghetti', 0.18, 0.18, 'szt', false),
  ('h12', 'passata', 0.44, 0.44, 'szt', false),
  ('h12', 'cebula', 0.06, 0.06, 'kg', false),
  ('h12', 'marchew', 0.05, 0.05, 'kg', false),
  ('h12', 'czosnek', 0.12, 0.12, 'szt', false),
  ('h12', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h12', 'parmezan', 0.015, 0.015, 'kg', false),
  ('h13', 'kurczak', 0.15, 0.15, 'kg', false),
  ('h13', 'penne', 0.16, 0.16, 'szt', false),
  ('h13', 'pesto', 0.158, 0.158, 'szt', false),
  ('h13', 'pomidory', 0.1, 0.1, 'kg', false),
  ('h13', 'szpinak', 0.5, 0.5, 'szt', false),
  ('h13', 'parmezan', 0.015, 0.015, 'kg', false),
  ('h14', 'tunczyk', 1, 1, 'szt', false),
  ('h14', 'penne', 0.16, 0.16, 'szt', false),
  ('h14', 'pomidory', 0.15, 0.15, 'kg', false),
  ('h14', 'passata', 0.24, 0.24, 'szt', false),
  ('h14', 'czosnek', 0.12, 0.12, 'szt', false),
  ('h14', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h15', 'kielbasa', 0.15, 0.15, 'kg', false),
  ('h15', 'penne', 0.16, 0.16, 'szt', false),
  ('h15', 'pomidory-puszka', 0.5, 0.5, 'szt', false),
  ('h15', 'cebula', 0.06, 0.06, 'kg', false),
  ('h15', 'szpinak', 0.5, 0.5, 'szt', false),
  ('h15', 'mozzarella', 0.03, 0.03, 'kg', false),
  ('h15', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h16', 'penne', 0.15, 0.15, 'szt', false),
  ('h16', 'ricotta', 0.1, 0.1, 'kg', false),
  ('h16', 'szpinak', 1, 1, 'szt', false),
  ('h16', 'passata', 0.36, 0.36, 'szt', false),
  ('h16', 'mozzarella', 0.04, 0.04, 'kg', false),
  ('h16', 'czosnek', 0.12, 0.12, 'szt', false),
  ('h16', 'parmezan', 0.01, 0.01, 'kg', false),
  ('h17', 'kurczak', 0.16, 0.16, 'kg', false),
  ('h17', 'penne', 0.16, 0.16, 'szt', false),
  ('h17', 'brokuly', 0.375, 0.375, 'szt', false),
  ('h17', 'czosnek', 0.24, 0.24, 'szt', false),
  ('h17', 'parmezan', 0.02, 0.02, 'kg', false),
  ('h17', 'oliwa', 0.01, 0.01, 'szt', true),
  ('h17', 'cytryna', 1, 1, 'szt', false),
  ('h18', 'gnocchi', 0.25, 0.25, 'kg', false),
  ('h18', 'pomidory', 0.18, 0.18, 'kg', false),
  ('h18', 'mozzarella', 0.08, 0.08, 'kg', false),
  ('h18', 'passata', 0.24, 0.24, 'szt', false),
  ('h18', 'czosnek', 0.12, 0.12, 'szt', false),
  ('h18', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h19', 'penne', 0.15, 0.15, 'szt', false),
  ('h19', 'tunczyk', 1, 1, 'szt', false),
  ('h19', 'pomidory', 0.12, 0.12, 'kg', false),
  ('h19', 'ogorki', 0.08, 0.08, 'kg', false),
  ('h19', 'oliwki', 0.125, 0.125, 'szt', false),
  ('h19', 'feta', 0.2, 0.2, 'szt', false),
  ('h19', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h19', 'cytryna', 1, 1, 'szt', false),
  ('h20', 'kurczak', 0.15, 0.15, 'kg', false),
  ('h20', 'penne', 0.16, 0.16, 'szt', false),
  ('h20', 'passata', 0.4, 0.4, 'szt', false),
  ('h20', 'czosnek', 0.12, 0.12, 'szt', false),
  ('h20', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h20', 'parmezan', 0.015, 0.015, 'kg', false),
  ('h21', 'kurczak', 0.15, 0.15, 'kg', false),
  ('h21', 'penne', 0.16, 0.16, 'szt', false),
  ('h21', 'pieczarki', 0.15, 0.15, 'kg', false),
  ('h21', 'smietanka', 0.4, 0.4, 'szt', false),
  ('h21', 'parmezan', 0.02, 0.02, 'kg', false),
  ('h21', 'czosnek', 0.12, 0.12, 'szt', false),
  ('h21', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h22', 'kurczak', 0.16, 0.16, 'kg', false),
  ('h22', 'fasola-biala', 0.542, 0.542, 'szt', false),
  ('h22', 'pomidory-puszka', 0.45, 0.45, 'szt', false),
  ('h22', 'szpinak', 0.7, 0.7, 'szt', false),
  ('h22', 'cebula', 0.05, 0.05, 'kg', false),
  ('h22', 'czosnek', 0.12, 0.12, 'szt', false),
  ('h22', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h23', 'indyk', 0.18, 0.18, 'kg', false),
  ('h23', 'jaja', 0.1, 0.1, 'opak', false),
  ('h23', 'bulka-tarta', 0.025, 0.025, 'kg', false),
  ('h23', 'passata', 0.44, 0.44, 'szt', false),
  ('h23', 'cebula', 0.05, 0.05, 'kg', false),
  ('h23', 'czosnek', 0.12, 0.12, 'szt', false),
  ('h23', 'parmezan', 0.015, 0.015, 'kg', false),
  ('h23', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h24', 'kurczak', 0.17, 0.17, 'kg', false),
  ('h24', 'mozzarella', 0.06, 0.06, 'kg', false),
  ('h24', 'pomidory', 0.15, 0.15, 'kg', false),
  ('h24', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h24', 'salata', 0.4, 0.4, 'szt', false),
  ('h25', 'kurczak', 0.15, 0.15, 'kg', false),
  ('h25', 'spaghetti', 0.16, 0.16, 'szt', false),
  ('h25', 'cytryna', 1, 1, 'szt', false),
  ('h25', 'czosnek', 0.12, 0.12, 'szt', false),
  ('h25', 'parmezan', 0.02, 0.02, 'kg', false),
  ('h25', 'oliwa', 0.01, 0.01, 'szt', true),
  ('h26', 'kurczak', 0.17, 0.17, 'kg', false),
  ('h26', 'ryz', 0.064, 0.064, 'kg', false),
  ('h26', 'jogurt-grecki', 0.4, 0.4, 'szt', false),
  ('h26', 'passata', 0.36, 0.36, 'szt', false),
  ('h26', 'cebula', 0.06, 0.06, 'kg', false),
  ('h26', 'czosnek', 0.12, 0.12, 'szt', false),
  ('h26', 'maslo', 0.05, 0.05, 'szt', true),
  ('h27', 'kurczak', 0.17, 0.17, 'kg', false),
  ('h27', 'jogurt-grecki', 0.467, 0.467, 'szt', false),
  ('h27', 'passata', 0.4, 0.4, 'szt', false),
  ('h27', 'cebula', 0.06, 0.06, 'kg', false),
  ('h27', 'czosnek', 0.12, 0.12, 'szt', false),
  ('h27', 'ryz', 0.06, 0.06, 'kg', false),
  ('h27', 'maslo', 0.025, 0.025, 'szt', true),
  ('h28', 'kurczak', 0.16, 0.16, 'kg', false),
  ('h28', 'mleczko', 0.375, 0.375, 'szt', false),
  ('h28', 'ryz', 0.06, 0.06, 'kg', false),
  ('h28', 'cebula', 0.06, 0.06, 'kg', false),
  ('h28', 'papryka', 0.08, 0.08, 'kg', false),
  ('h28', 'czosnek', 0.12, 0.12, 'szt', false),
  ('h28', 'limonka', 0.5, 0.5, 'szt', false),
  ('h29', 'ciecierzyca', 0.75, 0.75, 'szt', false),
  ('h29', 'szpinak', 1.2, 1.2, 'szt', false),
  ('h29', 'mleczko', 0.25, 0.25, 'szt', false),
  ('h29', 'pomidory-puszka', 0.45, 0.45, 'szt', false),
  ('h29', 'cebula', 0.06, 0.06, 'kg', false),
  ('h29', 'czosnek', 0.12, 0.12, 'szt', false),
  ('h29', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h30', 'soczewica', 0.1, 0.1, 'kg', false),
  ('h30', 'ryz', 0.052, 0.052, 'kg', false),
  ('h30', 'cebula', 0.06, 0.06, 'kg', false),
  ('h30', 'pomidory-puszka', 0.3, 0.3, 'szt', false),
  ('h30', 'czosnek', 0.12, 0.12, 'szt', false),
  ('h30', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h31', 'kurczak', 0.16, 0.16, 'kg', false),
  ('h31', 'ziemniaki', 0.2, 0.2, 'kg', false),
  ('h31', 'cukinia', 0.1, 0.1, 'kg', false),
  ('h31', 'marchew', 0.08, 0.08, 'kg', false),
  ('h31', 'oliwa', 0.01, 0.01, 'szt', true),
  ('h31', 'jogurt', 0.267, 0.267, 'szt', false),
  ('h32', 'soczewica', 0.1, 0.1, 'kg', false),
  ('h32', 'passata', 0.44, 0.44, 'szt', false),
  ('h32', 'cebula', 0.06, 0.06, 'kg', false),
  ('h32', 'szpinak', 0.7, 0.7, 'szt', false),
  ('h32', 'czosnek', 0.12, 0.12, 'szt', false),
  ('h32', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h33', 'kurczak', 0.16, 0.16, 'kg', false),
  ('h33', 'ziemniaki', 0.22, 0.22, 'kg', false),
  ('h33', 'pomidory-puszka', 0.45, 0.45, 'szt', false),
  ('h33', 'cebula', 0.06, 0.06, 'kg', false),
  ('h33', 'groch', 0.07, 0.07, 'kg', false),
  ('h33', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h34', 'ciecierzyca', 0.667, 0.667, 'szt', false),
  ('h34', 'ryz', 0.056, 0.056, 'kg', false),
  ('h34', 'ogorki', 0.08, 0.08, 'kg', false),
  ('h34', 'pomidory', 0.1, 0.1, 'kg', false),
  ('h34', 'szpinak', 0.5, 0.5, 'szt', false),
  ('h34', 'jogurt', 0.4, 0.4, 'szt', false),
  ('h34', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h35', 'kurczak', 0.15, 0.15, 'kg', false),
  ('h35', 'tortilla', 0.167, 0.167, 'opak', false),
  ('h35', 'jogurt-grecki', 0.333, 0.333, 'szt', false),
  ('h35', 'ogorki', 0.07, 0.07, 'kg', false),
  ('h35', 'pomidory', 0.07, 0.07, 'kg', false),
  ('h35', 'czosnek', 0.12, 0.12, 'szt', false),
  ('h35', 'salata', 0.25, 0.25, 'szt', false),
  ('h36', 'soczewica', 0.1, 0.1, 'kg', false),
  ('h36', 'mleczko', 0.3, 0.3, 'szt', false),
  ('h36', 'szpinak', 0.8, 0.8, 'szt', false),
  ('h36', 'cebula', 0.06, 0.06, 'kg', false),
  ('h36', 'czosnek', 0.12, 0.12, 'szt', false),
  ('h36', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h37', 'jaja', 0.3, 0.3, 'opak', false),
  ('h37', 'pomidory-puszka', 0.55, 0.55, 'szt', false),
  ('h37', 'cebula', 0.05, 0.05, 'kg', false),
  ('h37', 'szpinak', 0.5, 0.5, 'szt', false),
  ('h37', 'ciecierzyca', 0.25, 0.25, 'szt', false),
  ('h37', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h38', 'kurczak', 0.17, 0.17, 'kg', false),
  ('h38', 'ryz', 0.064, 0.064, 'kg', false),
  ('h38', 'jogurt-grecki', 0.533, 0.533, 'szt', false),
  ('h38', 'orzechy', 0.02, 0.02, 'kg', false),
  ('h38', 'passata', 0.32, 0.32, 'szt', false),
  ('h38', 'cebula', 0.06, 0.06, 'kg', false),
  ('h38', 'czosnek', 0.12, 0.12, 'szt', false),
  ('h38', 'maslo', 0.025, 0.025, 'szt', true),
  ('h39', 'indyk', 0.18, 0.18, 'kg', false),
  ('h39', 'jaja', 0.1, 0.1, 'opak', false),
  ('h39', 'bulka-tarta', 0.02, 0.02, 'kg', false),
  ('h39', 'mleczko', 0.3, 0.3, 'szt', false),
  ('h39', 'passata', 0.24, 0.24, 'szt', false),
  ('h39', 'cebula', 0.05, 0.05, 'kg', false),
  ('h39', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h40', 'ciecierzyca', 0.625, 0.625, 'szt', false),
  ('h40', 'kalafior', 0.25, 0.25, 'szt', false),
  ('h40', 'marchew', 0.08, 0.08, 'kg', false),
  ('h40', 'groch', 0.07, 0.07, 'kg', false),
  ('h40', 'pomidory-puszka', 0.45, 0.45, 'szt', false),
  ('h40', 'mleczko', 0.25, 0.25, 'szt', false),
  ('h40', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h41', 'kurczak', 0.16, 0.16, 'kg', false),
  ('h41', 'ryz', 0.068, 0.068, 'kg', false),
  ('h41', 'teriyaki', 0.16, 0.16, 'szt', false),
  ('h41', 'brokuly', 0.3, 0.3, 'szt', false),
  ('h41', 'marchew', 0.06, 0.06, 'kg', false),
  ('h41', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h42', 'wolowina', 0.16, 0.16, 'kg', false),
  ('h42', 'brokuly', 0.45, 0.45, 'szt', false),
  ('h42', 'ryz', 0.06, 0.06, 'kg', false),
  ('h42', 'czosnek', 0.12, 0.12, 'szt', false),
  ('h43', 'ryz', 0.08, 0.08, 'kg', false),
  ('h43', 'kurczak', 0.13, 0.13, 'kg', false),
  ('h43', 'jaja', 0.2, 0.2, 'opak', false),
  ('h43', 'groch', 0.07, 0.07, 'kg', false),
  ('h43', 'marchew', 0.06, 0.06, 'kg', false),
  ('h44', 'ryz', 0.08, 0.08, 'kg', false),
  ('h44', 'jaja', 0.2, 0.2, 'opak', false),
  ('h44', 'groch', 0.07, 0.07, 'kg', false),
  ('h44', 'marchew', 0.06, 0.06, 'kg', false),
  ('h44', 'kukurydza', 0.429, 0.429, 'szt', false),
  ('h44', 'cebula', 0.05, 0.05, 'kg', false),
  ('h45', 'kurczak', 0.16, 0.16, 'kg', false),
  ('h45', 'ryz', 0.068, 0.068, 'kg', false),
  ('h45', 'chili-sos', 0.18, 0.18, 'szt', false),
  ('h45', 'papryka', 0.08, 0.08, 'kg', false),
  ('h45', 'brokuly', 0.25, 0.25, 'szt', false),
  ('h45', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h45', 'limonka', 0.5, 0.5, 'szt', false),
  ('h46', 'makaron', 0.09, 0.09, 'kg', false),
  ('h46', 'kurczak', 0.15, 0.15, 'kg', false),
  ('h46', 'brokuly', 0.25, 0.25, 'szt', false),
  ('h46', 'marchew', 0.06, 0.06, 'kg', false),
  ('h46', 'czosnek', 0.12, 0.12, 'szt', false),
  ('h47', 'wolowina', 0.16, 0.16, 'kg', false),
  ('h47', 'makaron', 0.09, 0.09, 'kg', false),
  ('h47', 'papryka', 0.08, 0.08, 'kg', false),
  ('h47', 'cebula', 0.05, 0.05, 'kg', false),
  ('h47', 'ostryga', 0.06, 0.06, 'szt', false),
  ('h47', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h48', 'kurczak', 0.16, 0.16, 'kg', false),
  ('h48', 'ryz', 0.068, 0.068, 'kg', false),
  ('h48', 'miod', 0.041, 0.041, 'szt', false),
  ('h48', 'czosnek', 0.12, 0.12, 'szt', false),
  ('h48', 'brokuly', 0.25, 0.25, 'szt', false),
  ('h48', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h49', 'kurczak', 0.15, 0.15, 'kg', false),
  ('h49', 'makaron', 0.09, 0.09, 'kg', false),
  ('h49', 'maslo-orzechowe', 0.071, 0.071, 'szt', false),
  ('h49', 'limonka', 0.5, 0.5, 'szt', false),
  ('h49', 'czosnek', 0.12, 0.12, 'szt', false),
  ('h49', 'ogorki', 0.08, 0.08, 'kg', false),
  ('h49', 'marchew', 0.05, 0.05, 'kg', false),
  ('h50', 'ramen', 0.08, 0.08, 'kg', false),
  ('h50', 'jaja', 0.2, 0.2, 'opak', false),
  ('h50', 'pieczarki', 0.1, 0.1, 'kg', false),
  ('h50', 'szpinak', 0.6, 0.6, 'szt', false),
  ('h50', 'kukurydza', 0.429, 0.429, 'szt', false),
  ('h50', 'bulion', 0.4, 0.4, 'l', false),
  ('h50', 'cebula', 0.05, 0.05, 'kg', false),
  ('h51', 'kurczak', 0.16, 0.16, 'kg', false),
  ('h51', 'ryz', 0.068, 0.068, 'kg', false),
  ('h51', 'brokuly', 0.25, 0.25, 'szt', false),
  ('h51', 'marchew', 0.06, 0.06, 'kg', false),
  ('h51', 'cebula', 0.05, 0.05, 'kg', false),
  ('h52', 'kurczak', 0.16, 0.16, 'kg', false),
  ('h52', 'ryz', 0.068, 0.068, 'kg', false),
  ('h52', 'miod', 0.041, 0.041, 'szt', false),
  ('h52', 'czosnek', 0.12, 0.12, 'szt', false),
  ('h52', 'brokuly', 0.3, 0.3, 'szt', false),
  ('h52', 'papryka', 0.07, 0.07, 'kg', false),
  ('h52', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h53', 'wolowina', 0.16, 0.16, 'kg', false),
  ('h53', 'ryz', 0.068, 0.068, 'kg', false),
  ('h53', 'gochujang', 0.08, 0.08, 'szt', false),
  ('h53', 'ogorki', 0.08, 0.08, 'kg', false),
  ('h53', 'marchew', 0.06, 0.06, 'kg', false),
  ('h53', 'cebula', 0.05, 0.05, 'kg', false),
  ('h54', 'losos', 0.17, 0.17, 'kg', false),
  ('h54', 'ryz', 0.068, 0.068, 'kg', false),
  ('h54', 'teriyaki', 0.14, 0.14, 'szt', false),
  ('h54', 'brokuly', 0.375, 0.375, 'szt', false),
  ('h54', 'limonka', 0.5, 0.5, 'szt', false),
  ('h55', 'kurczak', 0.15, 0.15, 'kg', false),
  ('h55', 'udon', 0.2, 0.2, 'kg', false),
  ('h55', 'papryka', 0.06, 0.06, 'kg', false),
  ('h55', 'marchew', 0.06, 0.06, 'kg', false),
  ('h55', 'brokuly', 0.15, 0.15, 'szt', false),
  ('h55', 'czosnek', 0.12, 0.12, 'szt', false),
  ('h56', 'kurczak', 0.16, 0.16, 'kg', false),
  ('h56', 'quinoa', 0.05, 0.05, 'kg', false),
  ('h56', 'ogorki', 0.08, 0.08, 'kg', false),
  ('h56', 'pomidory', 0.1, 0.1, 'kg', false),
  ('h56', 'feta', 0.2, 0.2, 'szt', false),
  ('h56', 'ciecierzyca', 0.292, 0.292, 'szt', false),
  ('h56', 'oliwa', 0.01, 0.01, 'szt', true),
  ('h56', 'cytryna', 1, 1, 'szt', false),
  ('h57', 'udka', 0.18, 0.18, 'kg', false),
  ('h57', 'ziemniaki', 0.25, 0.25, 'kg', false),
  ('h57', 'cytryna', 1, 1, 'szt', false),
  ('h57', 'czosnek', 0.12, 0.12, 'szt', false),
  ('h57', 'oliwa', 0.01, 0.01, 'szt', true),
  ('h57', 'ogorki', 0.08, 0.08, 'kg', false),
  ('h58', 'kurczak', 0.15, 0.15, 'kg', false),
  ('h58', 'salata', 0.6, 0.6, 'szt', false),
  ('h58', 'ogorki', 0.08, 0.08, 'kg', false),
  ('h58', 'pomidory', 0.1, 0.1, 'kg', false),
  ('h58', 'feta', 0.2, 0.2, 'szt', false),
  ('h58', 'oliwki', 0.125, 0.125, 'szt', false),
  ('h58', 'oliwa', 0.01, 0.01, 'szt', true),
  ('h58', 'cytryna', 1, 1, 'szt', false),
  ('h59', 'tunczyk', 1, 1, 'szt', false),
  ('h59', 'fasola-biala', 0.583, 0.583, 'szt', false),
  ('h59', 'pomidory', 0.12, 0.12, 'kg', false),
  ('h59', 'cebula', 0.03, 0.03, 'kg', false),
  ('h59', 'oliwa', 0.01, 0.01, 'szt', true),
  ('h59', 'cytryna', 1, 1, 'szt', false),
  ('h60', 'ciecierzyca', 0.667, 0.667, 'szt', false),
  ('h60', 'quinoa', 0.043, 0.043, 'kg', false),
  ('h60', 'ogorki', 0.08, 0.08, 'kg', false),
  ('h60', 'pomidory', 0.1, 0.1, 'kg', false),
  ('h60', 'szpinak', 0.5, 0.5, 'szt', false),
  ('h60', 'feta', 0.2, 0.2, 'szt', false),
  ('h60', 'oliwa', 0.01, 0.01, 'szt', true),
  ('h60', 'cytryna', 1, 1, 'szt', false),
  ('h61', 'losos', 0.17, 0.17, 'kg', false),
  ('h61', 'cukinia', 0.15, 0.15, 'kg', false),
  ('h61', 'papryka', 0.1, 0.1, 'kg', false),
  ('h61', 'brokuly', 0.3, 0.3, 'szt', false),
  ('h61', 'cytryna', 1, 1, 'szt', false),
  ('h61', 'czosnek', 0.12, 0.12, 'szt', false),
  ('h61', 'oliwa', 0.01, 0.01, 'szt', true),
  ('h62', 'kurczak', 0.17, 0.17, 'kg', false),
  ('h62', 'pita', 1, 1, 'szt', false),
  ('h62', 'ryz', 0.052, 0.052, 'kg', false),
  ('h62', 'ogorki', 0.08, 0.08, 'kg', false),
  ('h62', 'pomidory', 0.08, 0.08, 'kg', false),
  ('h62', 'jogurt-grecki', 0.4, 0.4, 'szt', false),
  ('h62', 'czosnek', 0.12, 0.12, 'szt', false),
  ('h62', 'cytryna', 1, 1, 'szt', false),
  ('h63', 'indyk', 0.18, 0.18, 'kg', false),
  ('h63', 'jaja', 0.1, 0.1, 'opak', false),
  ('h63', 'bulka-tarta', 0.02, 0.02, 'kg', false),
  ('h63', 'jogurt-grecki', 0.533, 0.533, 'szt', false),
  ('h63', 'ogorki', 0.1, 0.1, 'kg', false),
  ('h63', 'czosnek', 0.12, 0.12, 'szt', false),
  ('h63', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h64', 'penne', 0.15, 0.15, 'szt', false),
  ('h64', 'pomidory', 0.12, 0.12, 'kg', false),
  ('h64', 'ogorki', 0.08, 0.08, 'kg', false),
  ('h64', 'oliwki', 0.125, 0.125, 'szt', false),
  ('h64', 'feta', 0.25, 0.25, 'szt', false),
  ('h64', 'cebula', 0.03, 0.03, 'kg', false),
  ('h64', 'oliwa', 0.01, 0.01, 'szt', true),
  ('h64', 'cytryna', 1, 1, 'szt', false),
  ('h65', 'penne', 0.16, 0.16, 'szt', false),
  ('h65', 'feta', 0.4, 0.4, 'szt', false),
  ('h65', 'pomidory', 0.2, 0.2, 'kg', false),
  ('h65', 'czosnek', 0.12, 0.12, 'szt', false),
  ('h65', 'szpinak', 0.6, 0.6, 'szt', false),
  ('h65', 'oliwa', 0.01, 0.01, 'szt', true),
  ('h66', 'tunczyk', 1, 1, 'szt', false),
  ('h66', 'jaja', 0.2, 0.2, 'opak', false),
  ('h66', 'quinoa', 0.04, 0.04, 'kg', false),
  ('h66', 'ogorki', 0.08, 0.08, 'kg', false),
  ('h66', 'pomidory', 0.1, 0.1, 'kg', false),
  ('h66', 'oliwki', 0.1, 0.1, 'szt', false),
  ('h66', 'feta', 0.15, 0.15, 'szt', false),
  ('h66', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h67', 'kuskus', 0.08, 0.08, 'kg', false),
  ('h67', 'cukinia', 0.12, 0.12, 'kg', false),
  ('h67', 'papryka', 0.1, 0.1, 'kg', false),
  ('h67', 'baklazan', 0.1, 0.1, 'kg', false),
  ('h67', 'feta', 0.25, 0.25, 'szt', false),
  ('h67', 'oliwa', 0.01, 0.01, 'szt', true),
  ('h68', 'kurczak', 0.15, 0.15, 'kg', false),
  ('h68', 'kuskus', 0.08, 0.08, 'kg', false),
  ('h68', 'cytryna', 1, 1, 'szt', false),
  ('h68', 'cukinia', 0.1, 0.1, 'kg', false),
  ('h68', 'ciecierzyca', 0.292, 0.292, 'szt', false),
  ('h68', 'oliwa', 0.01, 0.01, 'szt', true),
  ('h69', 'papryka', 0.3, 0.3, 'kg', false),
  ('h69', 'indyk', 0.16, 0.16, 'kg', false),
  ('h69', 'ryz', 0.048, 0.048, 'kg', false),
  ('h69', 'pomidory', 0.12, 0.12, 'kg', false),
  ('h69', 'cebula', 0.05, 0.05, 'kg', false),
  ('h69', 'feta', 0.15, 0.15, 'szt', false),
  ('h69', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h70', 'kurczak', 0.15, 0.15, 'kg', false),
  ('h70', 'ciecierzyca', 0.542, 0.542, 'szt', false),
  ('h70', 'ziemniaki', 0.15, 0.15, 'kg', false),
  ('h70', 'marchew', 0.08, 0.08, 'kg', false),
  ('h70', 'pomidory', 0.2, 0.2, 'kg', false),
  ('h70', 'cebula', 0.06, 0.06, 'kg', false),
  ('h70', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h71', 'kurczak', 0.17, 0.17, 'kg', false),
  ('h71', 'ziemniaki', 0.25, 0.25, 'kg', false),
  ('h71', 'jaja', 0.1, 0.1, 'opak', false),
  ('h71', 'bulka-tarta', 0.03, 0.03, 'kg', false),
  ('h71', 'oliwa', 0.01, 0.01, 'szt', true),
  ('h71', 'ogorki', 0.1, 0.1, 'kg', false),
  ('h72', 'kurczak', 0.15, 0.15, 'kg', false),
  ('h72', 'marchew', 0.1, 0.1, 'kg', false),
  ('h72', 'seler', 0.06, 0.06, 'kg', false),
  ('h72', 'ziemniaki', 0.18, 0.18, 'kg', false),
  ('h72', 'cebula', 0.06, 0.06, 'kg', false),
  ('h72', 'bulion', 0.6, 0.6, 'l', false),
  ('h73', 'pomidory', 0.4, 0.4, 'kg', false),
  ('h73', 'ryz', 0.04, 0.04, 'kg', false),
  ('h73', 'cebula', 0.06, 0.06, 'kg', false),
  ('h73', 'marchew', 0.06, 0.06, 'kg', false),
  ('h73', 'bulion', 0.4, 0.4, 'l', false),
  ('h73', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h73', 'jogurt', 0.267, 0.267, 'szt', false),
  ('h74', 'ziemniaki', 0.3, 0.3, 'kg', false),
  ('h74', 'jaja', 0.2, 0.2, 'opak', false),
  ('h74', 'cebula', 0.06, 0.06, 'kg', false),
  ('h74', 'jogurt-grecki', 0.333, 0.333, 'szt', false),
  ('h74', 'oliwa', 0.01, 0.01, 'szt', true),
  ('h75', 'kurczak', 0.13, 0.13, 'kg', false),
  ('h75', 'peczak', 0.06, 0.06, 'kg', false),
  ('h75', 'marchew', 0.08, 0.08, 'kg', false),
  ('h75', 'seler', 0.06, 0.06, 'kg', false),
  ('h75', 'cebula', 0.06, 0.06, 'kg', false),
  ('h75', 'bulion', 0.6, 0.6, 'l', false),
  ('h76', 'udka', 0.17, 0.17, 'kg', false),
  ('h76', 'kapusta', 0.25, 0.25, 'kg', false),
  ('h76', 'ziemniaki', 0.15, 0.15, 'kg', false),
  ('h76', 'marchew', 0.07, 0.07, 'kg', false),
  ('h76', 'cebula', 0.06, 0.06, 'kg', false),
  ('h76', 'pomidory', 0.15, 0.15, 'kg', false),
  ('h76', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h77', 'indyk', 0.18, 0.18, 'kg', false),
  ('h77', 'jaja', 0.1, 0.1, 'opak', false),
  ('h77', 'bulka-tarta', 0.02, 0.02, 'kg', false),
  ('h77', 'ziemniaki', 0.25, 0.25, 'kg', false),
  ('h77', 'jogurt-grecki', 0.333, 0.333, 'szt', false),
  ('h77', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h78', 'kurczak', 0.16, 0.16, 'kg', false),
  ('h78', 'kasza', 0.06, 0.06, 'kg', false),
  ('h78', 'ogorki', 0.08, 0.08, 'kg', false),
  ('h78', 'marchew', 0.07, 0.07, 'kg', false),
  ('h78', 'cebula', 0.05, 0.05, 'kg', false),
  ('h78', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h79', 'udka', 0.17, 0.17, 'kg', false),
  ('h79', 'kiszona', 0.25, 0.25, 'kg', false),
  ('h79', 'ziemniaki', 0.18, 0.18, 'kg', false),
  ('h79', 'cebula', 0.06, 0.06, 'kg', false),
  ('h79', 'jablko', 0.06, 0.06, 'kg', false),
  ('h79', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h80', 'ziemniaki', 0.25, 0.25, 'kg', false),
  ('h80', 'jaja', 0.3, 0.3, 'opak', false),
  ('h80', 'cebula', 0.05, 0.05, 'kg', false),
  ('h80', 'maslo', 0.025, 0.025, 'szt', true),
  ('h80', 'ogorki', 0.08, 0.08, 'kg', false),
  ('h81', 'kurczak', 0.15, 0.15, 'kg', false),
  ('h81', 'cukinia', 0.12, 0.12, 'kg', false),
  ('h81', 'papryka', 0.1, 0.1, 'kg', false),
  ('h81', 'pomidory', 0.2, 0.2, 'kg', false),
  ('h81', 'cebula', 0.06, 0.06, 'kg', false),
  ('h81', 'fasola', 0.333, 0.333, 'szt', false),
  ('h81', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h82', 'indyk', 0.18, 0.18, 'kg', false),
  ('h82', 'kasza', 0.06, 0.06, 'kg', false),
  ('h82', 'cebula', 0.06, 0.06, 'kg', false),
  ('h82', 'marchew', 0.07, 0.07, 'kg', false),
  ('h82', 'papryka', 0.08, 0.08, 'kg', false),
  ('h82', 'pomidory', 0.15, 0.15, 'kg', false),
  ('h82', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h83', 'twarog', 0.2, 0.2, 'kg', false),
  ('h83', 'ziemniaki', 0.25, 0.25, 'kg', false),
  ('h83', 'ogorki', 0.1, 0.1, 'kg', false),
  ('h83', 'rzodkiewka', 0.6, 0.6, 'szt', false),
  ('h83', 'jogurt-grecki', 0.333, 0.333, 'szt', false),
  ('h84', 'kasza', 0.064, 0.064, 'kg', false),
  ('h84', 'pieczarki', 0.18, 0.18, 'kg', false),
  ('h84', 'cebula', 0.06, 0.06, 'kg', false),
  ('h84', 'szpinak', 0.7, 0.7, 'szt', false),
  ('h84', 'twarog', 0.1, 0.1, 'kg', false),
  ('h84', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h85', 'kapusta', 0.25, 0.25, 'kg', false),
  ('h85', 'indyk', 0.18, 0.18, 'kg', false),
  ('h85', 'ryz', 0.04, 0.04, 'kg', false),
  ('h85', 'cebula', 0.05, 0.05, 'kg', false),
  ('h85', 'passata', 0.44, 0.44, 'szt', false),
  ('h85', 'jaja', 0.1, 0.1, 'opak', false),
  ('h85', 'czosnek', 0.12, 0.12, 'szt', false),
  ('h86', 'kurczak', 0.15, 0.15, 'kg', false),
  ('h86', 'peczak', 0.07, 0.07, 'kg', false),
  ('h86', 'pieczarki', 0.18, 0.18, 'kg', false),
  ('h86', 'cebula', 0.06, 0.06, 'kg', false),
  ('h86', 'parmezan', 0.02, 0.02, 'kg', false),
  ('h86', 'bulion', 0.4, 0.4, 'l', false),
  ('h86', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h87', 'indyk', 0.17, 0.17, 'kg', false),
  ('h87', 'cukinia', 0.12, 0.12, 'kg', false),
  ('h87', 'papryka', 0.1, 0.1, 'kg', false),
  ('h87', 'marchew', 0.07, 0.07, 'kg', false),
  ('h87', 'cebula', 0.05, 0.05, 'kg', false),
  ('h87', 'pomidory', 0.15, 0.15, 'kg', false),
  ('h87', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h88', 'ziemniaki', 0.3, 0.3, 'kg', false),
  ('h88', 'twarog', 0.18, 0.18, 'kg', false),
  ('h88', 'jogurt-grecki', 0.333, 0.333, 'szt', false),
  ('h88', 'maslo', 0.025, 0.025, 'szt', true),
  ('h89', 'ziemniaki', 0.18, 0.18, 'kg', false),
  ('h89', 'marchew', 0.1, 0.1, 'kg', false),
  ('h89', 'cukinia', 0.15, 0.15, 'kg', false),
  ('h89', 'kapusta', 0.15, 0.15, 'kg', false),
  ('h89', 'fasola-biala', 0.417, 0.417, 'szt', false),
  ('h89', 'pomidory', 0.2, 0.2, 'kg', false),
  ('h89', 'cebula', 0.06, 0.06, 'kg', false),
  ('h89', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h90', 'kurczak', 0.15, 0.15, 'kg', false),
  ('h90', 'kiszona', 0.25, 0.25, 'kg', false),
  ('h90', 'ziemniaki', 0.18, 0.18, 'kg', false),
  ('h90', 'cebula', 0.06, 0.06, 'kg', false),
  ('h90', 'jablko', 0.05, 0.05, 'kg', false),
  ('h90', 'musztarda', 0.05, 0.05, 'szt', false),
  ('h90', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h91', 'kurczak', 0.17, 0.17, 'kg', false),
  ('h91', 'bulka-burger', 1, 1, 'szt', false),
  ('h91', 'bulka-tarta', 0.035, 0.035, 'kg', false),
  ('h91', 'jaja', 0.1, 0.1, 'opak', false),
  ('h91', 'ziemniaki', 0.25, 0.25, 'kg', false),
  ('h91', 'salata', 0.25, 0.25, 'szt', false),
  ('h91', 'pomidory', 0.08, 0.08, 'kg', false),
  ('h91', 'jogurt-grecki', 0.267, 0.267, 'szt', false),
  ('h91', 'oliwa', 0.01, 0.01, 'szt', true),
  ('h92', 'kurczak', 0.17, 0.17, 'kg', false),
  ('h92', 'pita', 1, 1, 'szt', false),
  ('h92', 'jogurt-grecki', 0.533, 0.533, 'szt', false),
  ('h92', 'ogorki', 0.08, 0.08, 'kg', false),
  ('h92', 'pomidory', 0.08, 0.08, 'kg', false),
  ('h92', 'cebula', 0.03, 0.03, 'kg', false),
  ('h92', 'czosnek', 0.12, 0.12, 'szt', false),
  ('h92', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h93', 'kurczak', 0.16, 0.16, 'kg', false),
  ('h93', 'tortilla', 0.167, 0.167, 'opak', false),
  ('h93', 'bulka-tarta', 0.03, 0.03, 'kg', false),
  ('h93', 'jaja', 0.1, 0.1, 'opak', false),
  ('h93', 'salata', 0.3, 0.3, 'szt', false),
  ('h93', 'pomidory', 0.07, 0.07, 'kg', false),
  ('h93', 'jogurt-grecki', 0.267, 0.267, 'szt', false),
  ('h93', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h94', 'mielone', 0.16, 0.16, 'kg', false),
  ('h94', 'ryz', 0.06, 0.06, 'kg', false),
  ('h94', 'cheddar', 0.035, 0.035, 'kg', false),
  ('h94', 'salata', 0.4, 0.4, 'szt', false),
  ('h94', 'pomidory', 0.08, 0.08, 'kg', false),
  ('h94', 'ogorki-kiszone', 0.04, 0.04, 'kg', false),
  ('h94', 'cebula', 0.03, 0.03, 'kg', false),
  ('h94', 'sos-burger', 0.12, 0.12, 'szt', false),
  ('h95', 'kurczak', 0.15, 0.15, 'kg', false),
  ('h95', 'tortilla', 0.167, 0.167, 'opak', false),
  ('h95', 'salata', 0.4, 0.4, 'szt', false),
  ('h95', 'parmezan', 0.02, 0.02, 'kg', false),
  ('h95', 'jogurt-grecki', 0.333, 0.333, 'szt', false),
  ('h95', 'cytryna', 1, 1, 'szt', false),
  ('h95', 'czosnek', 0.12, 0.12, 'szt', false),
  ('h95', 'bulka-tarta', 0.02, 0.02, 'kg', false),
  ('h95', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h96', 'tortilla', 0.167, 0.167, 'opak', false),
  ('h96', 'passata', 0.16, 0.16, 'szt', false),
  ('h96', 'mozzarella', 0.07, 0.07, 'kg', false),
  ('h96', 'kurczak', 0.1, 0.1, 'kg', false),
  ('h96', 'papryka', 0.06, 0.06, 'kg', false),
  ('h96', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h97', 'kurczak', 0.17, 0.17, 'kg', false),
  ('h97', 'ryz', 0.06, 0.06, 'kg', false),
  ('h97', 'hummus', 0.25, 0.25, 'szt', false),
  ('h97', 'ogorki', 0.08, 0.08, 'kg', false),
  ('h97', 'pomidory', 0.1, 0.1, 'kg', false),
  ('h97', 'salata', 0.25, 0.25, 'szt', false),
  ('h97', 'tahini', 0.05, 0.05, 'szt', false),
  ('h98', 'ziemniaki', 0.35, 0.35, 'kg', false),
  ('h98', 'kurczak', 0.13, 0.13, 'kg', false),
  ('h98', 'cheddar', 0.05, 0.05, 'kg', false),
  ('h98', 'jogurt-grecki', 0.333, 0.333, 'szt', false),
  ('h98', 'cebula', 0.02, 0.02, 'kg', false),
  ('h98', 'oliwa', 0.005, 0.005, 'szt', true),
  ('h99', 'kurczak', 0.16, 0.16, 'kg', false),
  ('h99', 'ryz', 0.064, 0.064, 'kg', false),
  ('h99', 'majonez', 0.075, 0.075, 'szt', false),
  ('h99', 'sriracha', 0.075, 0.075, 'szt', false),
  ('h99', 'panko', 0.025, 0.025, 'kg', false),
  ('h99', 'jaja', 0.1, 0.1, 'opak', false),
  ('h99', 'ogorki', 0.08, 0.08, 'kg', false),
  ('h99', 'cebula', 0.05, 0.05, 'kg', false),
  ('h100', 'kurczak', 0.17, 0.17, 'kg', false),
  ('h100', 'tortilla', 0.167, 0.167, 'opak', false),
  ('h100', 'ryz', 0.048, 0.048, 'kg', false),
  ('h100', 'fasola-czarna', 0.333, 0.333, 'szt', false),
  ('h100', 'cheddar', 0.035, 0.035, 'kg', false),
  ('h100', 'salsa', 0.233, 0.233, 'szt', false),
  ('h100', 'awokado', 0.313, 0.313, 'szt', false),
  ('h100', 'jogurt-grecki', 0.267, 0.267, 'szt', false)
;

insert into recipe_pantry (recipe_id, name, grams) values
  ('h01', 'Kumin', 2),
  ('h01', 'Papryka mielona', 2),
  ('h01', 'Sól', 2),
  ('h02', 'Kumin', 2),
  ('h02', 'Papryka mielona', 2),
  ('h04', 'Chili', 1),
  ('h04', 'Kumin', 2),
  ('h04', 'Papryka mielona', 2),
  ('h05', 'Papryka mielona', 2),
  ('h05', 'Kumin', 2),
  ('h06', 'Papryka mielona', 2),
  ('h06', 'Kumin', 2),
  ('h08', 'Pieprz', 1),
  ('h09', 'Kumin', 2),
  ('h11', 'Zioła', 1),
  ('h14', 'Pietruszka', 3),
  ('h18', 'Bazylia', 2),
  ('h20', 'Chili', 1),
  ('h20', 'Pietruszka', 3),
  ('h22', 'Zioła', 1),
  ('h24', 'Bazylia', 2),
  ('h24', 'Glazura balsamiczna', 10),
  ('h25', 'Pietruszka', 3),
  ('h26', 'Garam masala', 2),
  ('h26', 'Curry', 3),
  ('h27', 'Garam masala', 2),
  ('h27', 'Papryka mielona', 2),
  ('h28', 'Curry', 3),
  ('h29', 'Curry', 3),
  ('h30', 'Kurkuma', 1),
  ('h30', 'Kumin', 2),
  ('h31', 'Curry', 3),
  ('h32', 'Kumin', 2),
  ('h32', 'Kurkuma', 1),
  ('h33', 'Curry', 3),
  ('h34', 'Curry', 3),
  ('h35', 'Papryka mielona', 2),
  ('h35', 'Kumin', 2),
  ('h36', 'Kurkuma', 1),
  ('h36', 'Kumin', 2),
  ('h37', 'Kumin', 2),
  ('h37', 'Chili', 1),
  ('h38', 'Garam masala', 2),
  ('h39', 'Curry', 3),
  ('h40', 'Curry', 3),
  ('h41', 'Sezam', 5),
  ('h42', 'Sos sojowy', 25),
  ('h42', 'Imbir', 8),
  ('h42', 'Olej sezamowy', 5),
  ('h42', 'Skrobia', 5),
  ('h43', 'Sos sojowy', 20),
  ('h43', 'Olej sezamowy', 5),
  ('h44', 'Sos sojowy', 15),
  ('h44', 'Olej sezamowy', 5),
  ('h46', 'Sos sojowy', 20),
  ('h46', 'Olej sezamowy', 5),
  ('h47', 'Sos sojowy', 25),
  ('h48', 'Sezam', 8),
  ('h48', 'Sos sojowy', 20),
  ('h48', 'Imbir', 8),
  ('h49', 'Sos sojowy', 20),
  ('h50', 'Sos sojowy', 15),
  ('h51', 'Imbir', 8),
  ('h51', 'Sos sojowy', 20),
  ('h51', 'Olej sezamowy', 5),
  ('h52', 'Sos sojowy', 20),
  ('h53', 'Sos sojowy', 15),
  ('h53', 'Sezam', 5),
  ('h54', 'Sezam', 5),
  ('h55', 'Sos sojowy', 25),
  ('h55', 'Imbir', 8),
  ('h55', 'Olej sezamowy', 5),
  ('h57', 'Oregano', 1),
  ('h59', 'Pietruszka', 3),
  ('h62', 'Oregano', 1),
  ('h63', 'Koperek', 2),
  ('h65', 'Bazylia', 2),
  ('h67', 'Zioła', 1),
  ('h68', 'Pietruszka', 3),
  ('h69', 'Oregano', 1),
  ('h70', 'Zioła', 1),
  ('h71', 'Mąka', 15),
  ('h72', 'Pietruszka', 3),
  ('h72', 'Liść laurowy', 1),
  ('h74', 'Mąka', 25),
  ('h74', 'Koperek', 2),
  ('h75', 'Pietruszka', 3),
  ('h76', 'Papryka mielona', 2),
  ('h77', 'Koperek', 2),
  ('h78', 'Papryka mielona', 2),
  ('h79', 'Kminek', 1),
  ('h80', 'Koperek', 2),
  ('h81', 'Papryka mielona', 2),
  ('h82', 'Papryka mielona', 2),
  ('h83', 'Koperek', 2),
  ('h83', 'Sól', 2),
  ('h83', 'Pieprz', 1),
  ('h84', 'Koperek', 2),
  ('h87', 'Zioła', 1),
  ('h88', 'Szczypiorek', 20),
  ('h88', 'Sól', 2),
  ('h88', 'Pieprz', 1),
  ('h92', 'Papryka mielona', 2),
  ('h92', 'Kumin', 2),
  ('h96', 'Oregano', 1),
  ('h97', 'Papryka mielona', 2)
;
